"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "en" | "ar"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "Who Are We?",
    "nav.news": "Latest News",
    "nav.programs": "Our Programs",
    "nav.success": "Success Stories",
    "nav.apply": "Apply for Grants",
    "nav.activities": "Previous Activities",
    "nav.testimonials": "Testimonials",
    "nav.contact": "Contact Us",
    "nav.media": "Media",
    "nav.media.success": "Success Stories",
    "nav.media.activities": "Previous Activities",
    "nav.media.testimonials": "Testimonials",
    "nav.donate": "Donate Now",
    "nav.donate.title": "Support Our Cause",
    "nav.donate.desc": "Help Palestinian students achieve their dreams",

    "hero.title": "Empowering Palestinian Students Worldwide",
    "hero.subtitle":
      "Providing scholarships, university admissions assistance, and academic support to help Palestinian students achieve their educational dreams.",
    "hero.cta.apply": "Apply for Scholarship",
    "hero.cta.explore": "Explore Programs",


    "about.widgt": "Values",
    "about.title":"Our Values",
    "about.subtitle":"IFPPS",
    "about.identity": "National Belonging",
    "about.identity.desc": "We operate from a deep commitment to the Palestinian cause, striving to instill national identity in everything we do.",
    "about.identity2":"Academic Excellence",
    "about.identity2.desc":"We support scientific and academic talent and encourage the continuous pursuit of excellence and knowledge",
    "about.identity3":"Justice and Equal Opportunity",
    "about.identity3.desc":"We believe in the necessity of providing opportunities to society based on competence and merit, without discrimination.",
    "about.identity4":"Transparency and Integrity",
    "about.identity4.desc":"We conduct our work with a spirit of clarity and accountability, maintaining mutual trust with our partners.",
    "about.identity5":"Sustainability",
    "about.identity5.desc":"We plan and operate with a forward-looking spirit that ensures a long-term positive impact on Palestinian society.",
    "about.identity6":"Youth Empowerment",
    "about.identity6.desc":"We believe in the importance of supporting and empowering young Palestinian academic talent, as they are the primary engine for building the future and achieving sustainable national development.",
    "about.identity7":"Initiative",
    "about.identity7.desc":"We constantly strive to identify student needs, present projects that meet these needs, and encourage students to launch community initiatives.",
    "about.cta":"About Us",

    "about.hero.title": "Who Are We?",
    "about.hero.description": "The Palestinian Support Fund is an independent, non-profit development entity that aims to support higher education in Palestine by investing in the potential of young academics. The Fund focuses on providing programs and initiatives that contribute to bridging the gap between educational outcomes and community needs by providing scholarships and facilitating access to nationally prioritized majors. It also works to create a knowledge network that brings together Palestinian talents within the country and abroad, within a comprehensive development vision.",
    "about.mission.tag": "Our Mission",
    "about.mission.title": "Empowering Through Education",
    "about.mission.text": "The Palestinian Support Fund aims to support outstanding Palestinian students to complete their postgraduate studies in vital specializations needed by Palestinian society, by offering targeted scholarships. The Fund seeks to achieve an effective link between the education sector and the requirements of economic and social development in Palestine. It also works to establish a network of Palestinian academic competencies inside and outside the country to support scientific research and contribute to the development of national institutions. The Fund believes in the importance of enhancing the role of youth in community activities through educational and awareness programs aimed at consolidating the concepts of interaction, social harmony, and national belonging.",
    "about.vision.tag": "Our Vision",
    "about.vision.title": "Building Future Leaders",
    "about.vision.text": "To elevate young Palestinian academic competencies across various fields essential to society and empower them to play a vital, effective role in building a strong, sustainable, and prosperous future for the State of Palestine.",
    "about.foundation.tag": "Foundation Identity",
    "about.foundation.title": "Our Story",
    "about.foundation.text1": "Established in 2015 in Istanbul, Turkey, the Isnad Foundation was founded by a group of educators and professionals who recognized the challenges faced by Palestinian students seeking higher education opportunities.",
    "about.foundation.text2": "What began as a small initiative providing scholarships to a handful of students has grown into a comprehensive support organization that has helped hundreds of Palestinian students access quality education across the globe.",
    "about.foundation.text3": "Our foundation is registered as a non-profit educational organization in Turkey, operating with full transparency and accountability to our donors and partners.",
    "about.team.tag": "Administrative Structure",
    "about.team.title": "Our Team",
    "about.team.viewAll": "View Full Team",
    "about.team.member1.name": "Dr. Mahmoud Abbas",
    "about.team.member1.title": "Executive Director",
    "about.team.member1.description": "Former university professor with 20+ years of experience in educational administration.",
    "about.team.member2.name": "Dr. Layla Khalid",
    "about.team.member2.title": "Academic Director",
    "about.team.member2.description": "Specializes in international education policy and student mentorship programs.",
    "about.team.member3.name": "Omar Farooq",
    "about.team.member3.title": "Financial Director",
    "about.team.member3.description": "Expert in non-profit financial management and scholarship fund administration.",

    "work.badget":"Educate. Empower. Connect.",
    "work.title":"The Foundation's areas of work",
    "work.subtitle":"Empowering Palestinian Youth Through Education, Innovation, and Connection",
    "card1.title":"Scholarships and Academic Support",
    "Card1.desc":"Providing scholarships to Palestinian youth in specializations needed by the labor market and society inside and outside Palestine.",
    "Card2.title":"Capacity Building and Professional Development",
    "Card2.desc":"Organizing training workshops, professional development programs, and consultations to prepare youth for the labor market and enhance their leadership and technical skills.",
    "Card3.title":"Scientific Research and Knowledge Contribution",
    "Card3.desc":"Funding and encouraging applied research related to national development, and establishing partnerships with universities and research centers.",
    "Card4.title":"Strengthening National Identity and Community Participation",
    "Card4.desc":"Implementing cultural, educational, and awareness programs aimed at instilling national values ​​and activating the role of youth in public life.",
    "Card5.title": "Building a network of Palestinian competencies",
    "Card5.desc": "linking local Palestinian competencies abroad, and activating bridges of communication between academics, researchers, and relevant institutions.",

    "footer.rights": "All rights reserved.",
    "footer.programs": "Programs",
    "footer.about": "About",
    "footer.contact": "Contact",

    "donate.hero.title": "Support Palestinian Students",
    "donate.hero.subtitle": "Your donation helps provide scholarships, educational support, and opportunities for Palestinian students worldwide.",
    "donate.form.title": "Make a Donation",
    "donate.form.amount": "Select Amount",
    "donate.form.custom": "Custom Amount",
    "donate.form.payment": "Payment Method",
    "donate.form.card": "Credit/Debit Card",
    "donate.form.bank": "Bank Transfer",
    "donate.form.button": "Donate Now",
    "donate.trust.secure": "Secure Payment",
    "donate.trust.tax": "Tax Deductible",
    "donate.impact.title": "Your Impact",
    "donate.impact.students": "Students Supported",
    "donate.impact.scholarships": "Scholarships Awarded",
    "donate.impact.countries": "Countries Reached",
    "donate.faq.title": "Frequently Asked Questions",
    "donate.faq.use": "How will my donation be used?",
    "donate.faq.use.answer": "Your donation directly supports Palestinian students through scholarships, educational programs, and academic support. We ensure transparency in fund allocation and provide regular updates on the impact of your contribution.",
    "donate.faq.tax": "Is my donation tax-deductible?",
    "donate.faq.tax.answer": "Yes, all donations to IFPPS are tax-deductible. We provide donation receipts for all contributions, which can be used for tax purposes in applicable jurisdictions.",
    "donate.faq.recurring": "Can I make a recurring donation?",
    "donate.faq.recurring.answer": "Yes, we offer monthly, quarterly, and annual recurring donation options. You can set up and manage your recurring donations through our secure payment system.",
    "donate.faq.track": "How can I track the impact of my donation?",
    "donate.faq.track.answer": "We provide regular updates through our newsletter and annual impact reports. You can also follow our success stories and student testimonials on our website and social media channels.",
    "donate.form.type": "Select Donation Type",
    "donate.form.general": "General Donation",
    "donate.form.specific": "Specific Program",
    "donate.form.select_program": "Select Program",
    "donate.form.choose_program": "Choose a program",
    "donate.form.distribution": "Financial Distribution",
    "donate.form.distribution_desc": "Your donation will be distributed as follows:",
    "donate.programs.scholarships": "Scholarships Program",
    "donate.programs.research": "Research & Development",
    "donate.programs.capacity": "Capacity Building",
    "donate.programs.pulse": "Pulse of Life Scholarship",
    "donate.programs.pulse.desc": "Full scholarships in medicine and health sciences for Palestinian students. Supporting 1,000 students over 5 years.",
    "donate.programs.talented": "Palestinian Talented Student",
    "donate.programs.talented.desc": "Supporting outstanding Palestinian students across various academic fields. 1,000 scholarships for exceptional leaders.",
    "donate.programs.sustainability": "Sustainability",
    "donate.programs.sustainability.desc": "200 scholarships in energy and agricultural engineering for Palestine's green future.",
    "donate.programs.justice": "Justice for Palestine",
    "donate.programs.justice.desc": "200 scholarships in political science and international relations for global advocacy.",
    "donate.programs.ibn-khaldun": "Ibn Khaldun",
    "donate.programs.ibn-khaldun.desc": "200 scholarships in sociology and psychology for understanding Palestinian society.",
    "donate.programs.duration": "Program Duration",
    "donate.programs.focus": "Field of Focus",

    // Sustainability Scholarship translations
    "sustainability.title": "Sustainability Scholarship Program",
    "sustainability.subtitle": "Towards Global Sovereignty and a Society Driving Its Own Development",
    "sustainability.scholarships": "Scholarships",
    "sustainability.years": "Years",
    "sustainability.majors": "Majors",
    "sustainability.about.title": "About the Program",
    "sustainability.about.desc": "The Sustainability Scholarship Program for Graduate Studies is a national initiative by the Isnad Foundation to support Palestinian students. It aims to qualify Palestinian talents in vital fields including sustainable energy, agriculture, and natural resources, to achieve national sovereignty in energy and food, and promote sustainable development in Palestine.",
    "sustainability.why.title": "Why the Sustainability Scholarship?",
    "sustainability.why.energy.title": "Heavy Reliance on Imported Energy",
    "sustainability.why.energy.desc": "Palestine relies on imported energy for 87.4% of its needs, making it vulnerable to crises and affecting economic and social development.",
    "sustainability.why.renewable.title": "Low Contribution of Renewable Energy",
    "sustainability.why.renewable.desc": "Despite Palestine's significant natural potential for renewable energy, its contribution to local production does not exceed 4.7%.",
    "sustainability.why.agriculture.title": "Agricultural Sector Challenges",
    "sustainability.why.agriculture.desc": "The Palestinian agricultural sector faces major challenges related to water scarcity, declining cultivated areas, and weak use of modern technologies in plant, animal, and food production.",
    "sustainability.why.occupation.title": "Impact of Occupation on Natural Resources",
    "sustainability.why.occupation.desc": "The occupation depletes Palestinian natural resources and limits the ability of Palestinians to invest in them.",
    "sustainability.why.programs.title": "Lack of Specialized Academic Programs",
    "sustainability.why.programs.desc": "There are few specialized academic programs in the fields of energy, agriculture, and natural resources.",
    "sustainability.why.research.title": "Lack of Applied Scientific Research",
    "sustainability.why.research.desc": "There is a lack of applied research that contributes to developing practical solutions to local problems.",
    "sustainability.objectives.title": "Our Objectives",
    "sustainability.objectives.subtitle": "Empowering a new generation to lead Palestine's sustainable future. Here's what we're striving for:",
    "sustainability.objectives.scholarships.title": "200 Full Scholarships",
    "sustainability.objectives.scholarships": "Award 200 full scholarships to outstanding Palestinian students in energy, agriculture, and natural resources—fueling the next wave of changemakers.",
    "sustainability.objectives.research.title": "Applied Research",
    "sustainability.objectives.research": "Ignite applied scientific research that delivers real solutions for a greener, more resilient Palestine.",
    "sustainability.objectives.knowledge.title": "Knowledge & Innovation",
    "sustainability.objectives.knowledge": "Boost Palestinian knowledge and innovation, connecting research to national priorities and real-world impact.",
    "sustainability.objectives.leaders.title": "Future Leaders",
    "sustainability.objectives.leaders": "Inspire and graduate leaders ready to drive sustainable development and positive change across Palestine.",
    "sustainability.financial.title": "Financial Support",
    "sustainability.financial.tuition.title": "Annual Tuition Fees",
    "sustainability.financial.tuition.desc": "The scholarship covers annual tuition fees.",
    "sustainability.financial.tuition.amount": "$3,000",
    "sustainability.financial.tuition.period": "per academic year",
    "sustainability.financial.living.title": "Annual Living Support",
    "sustainability.financial.living.desc": "Students receive a monthly living stipend.",
    "sustainability.financial.living.amount": "$200",
    "sustainability.financial.living.period": "per month ($2,400/year)",
    "sustainability.financial.housing.title": "Housing Support",
    "sustainability.financial.housing.desc": "If needed, the scholarship provides annual housing support.",
    "sustainability.financial.housing.amount": "$2,400",
    "sustainability.financial.housing.period": "per year",
    "sustainability.contact.title": "Contact Us",
    "sustainability.contact.desc": "For more information, please contact us:",
    "sustainability.apply": "Apply Now",
    "sustainability.download.en": "Download Program (EN)",
    "sustainability.download.ar": "Download Program (AR)",

    // Palestinian Talented Scholarship translations
    "talented.title": "Palestinian Talented",
    "talented.subtitle": "Excellence Scholarship Program",
    "talented.tagline": "🌟 Supporting Palestinian Talent: Our Collective Responsibility ⭐",
    "talented.scholarships": "Scholarships",
    "talented.areas": "Support Areas",
    "talented.pillars": "Financial Pillars",
    "talented.about.title": "About the Excellence Program",
    "talented.about.desc": "The \"Palestinian Talented Student Scholarship Program\" is a national initiative launched by the Isnad Foundation, offering 1,000 scholarships to outstanding students within Palestine across various academic fields. The program is designed to develop exceptional leaders across different academic fields and enable youth to achieve their full potential and serve society.",
    "talented.apply": "Apply for Talented Scholarship",
    "talented.download.en": "Download Program (EN)",
    "talented.download.ar": "تحميل البرنامج (AR)",
    "talented.why.title": "Why Support Palestinian Talent?",
    "talented.why.programs.title": "Lack of Specialized Programs",
    "talented.why.programs.desc": "There are no comprehensive national programs that support outstanding students and help them realize their potential in academic excellence and innovative projects.",
    "talented.why.environment.title": "Deprivation of an Appropriate Educational Environment",
    "talented.why.environment.desc": "Due to the lack of educational infrastructure in Palestine, many students are unable to access the resources and tools they need for development and academic success.",
    "talented.why.brain.title": "Brain Drain and Early Talent Loss",
    "talented.why.brain.desc": "The absence of early support mechanisms for exceptional students leads to the loss of many talented individuals who could have contributed to their communities.",
    "talented.why.development.title": "Lack of Talent Development Programs",
    "talented.why.development.desc": "Gifted Palestinian students often lack access to specialized programs that can nurture their talents and help them develop their skills and contribute to society.",
    "talented.why.occupation.title": "Occupation Practices Negatively Affect Well-being and Educational Opportunities",
    "talented.why.occupation.desc": "The ongoing occupation has a negative impact on the psychological and educational well-being of students. The constant stress and uncertainty make it difficult to focus on educational goals.",
    "talented.why.economic.title": "Challenging Economic Conditions Limit Access to Higher Education",
    "talented.why.economic.desc": "Financial constraints and challenging economic conditions prevent many Palestinian students from pursuing higher education and achieving their dreams.",
    "talented.why.achievement.title": "Outstanding Achievement is Difficult to Achieve Without Marginalized Support",
    "talented.why.achievement.desc": "To achieve outstanding results, students need comprehensive support that includes financial assistance, mentorship, and access to advanced educational resources.",
    "talented.why.infrastructure.title": "Limited Access to Quality Educational Infrastructure",
    "talented.why.infrastructure.desc": "Many Palestinian students lack access to modern educational facilities, advanced laboratories, and cutting-edge technology that are essential for academic excellence and innovation.",
    "talented.goals.title": "Our Goals",
    "talented.goals.scholarships": "Award 1,000 full scholarships to outstanding Palestinian students",
    "talented.goals.leaders": "Develop exceptional leaders across different academic fields",
    "talented.goals.potential": "Enable youth to achieve their full potential and serve society",
    "talented.financial.title": "Excellence Scholarship Financial Support",
    "talented.financial.academic.title": "Academic Excellence",
    "talented.financial.academic.desc": "Full coverage of academic excellence program costs",
    "talented.financial.academic.amount": "$2,500",
    "talented.financial.academic.period": "per academic year",
    "talented.financial.stipend.title": "Monthly Stipend",
    "talented.financial.stipend.desc": "Monthly living expenses support",
    "talented.financial.stipend.amount": "$200",
    "talented.financial.stipend.period": "monthly ($2,400/year)",
    "talented.financial.technology.title": "Technology Grant",
    "talented.financial.technology.desc": "One-time device purchase support",
    "talented.financial.technology.amount": "$300",
    "talented.financial.technology.period": "one-time grant",
    "talented.requirements.title": "Requirements",
    "talented.requirements.nationality": "Palestinian Nationality",
    "talented.requirements.average": "High School Average ≥ 90%",
    "talented.requirements.gpa": "GPA 3.00+",
    "talented.requirements.english": "English Proficiency Preferred",
    "talented.fields.title": "Fields of Study",
    "talented.fields.business": "Business Administration",
    "talented.fields.engineering": "Engineering",
    "talented.fields.education": "Education",
    "talented.fields.social": "Social Sciences",
    "talented.fields.computer": "Computer Science",
    "talented.fields.international": "International Relations",
    "talented.fields.economics": "Economics",
    "talented.fields.law": "Law",
    "talented.fields.psychology": "Psychology",
    "talented.fields.media": "Media & Communications",
    "talented.contact.title": "Contact Us",
    "talented.contact.desc": "For more information, reach out to us:",
    "talented.apply.now": "Apply Now",

    // Home page News & Announcements section
    "news.badge": "Latest Updates",
    "news.title": "News & Announcements",
    "news.subtitle": "Stay informed with our latest news, updates, and important announcements from the foundation.",
    "news.viewAll": "View All News",

    // Home page Our Programs section
    "programs.badge": "Scholarship Programs",
    "programs.title": "Our Programs",
    "programs.subtitle": "Empowering Palestinian students through specialized scholarship programs",
    "programs.pulse.title": "Pulse of Life Scholarship",
    "programs.pulse.category": "Medical & Health Sciences",
    "programs.pulse.scholarships": "1,000 Scholarships Over 5 Years",
    "programs.pulse.description": "A bold national initiative providing full scholarships in medicine and health sciences, focusing on rare and critical specializations to strengthen healthcare in Palestine.",
    "programs.pulse.focus": "Program Focus",
    "programs.pulse.features": "Key Features",
    "programs.pulse.medical": "Medical Education",
    "programs.pulse.innovation": "Healthcare Innovation",
    "programs.pulse.full": "Full Scholarships",
    "programs.pulse.years": "5-Year Program",
    "programs.talented.title": "Palestinian Talented scholarship",
    "programs.talented.category": "Excellence Scholarship",
    "programs.talented.scholarships": "1,000 Scholarships Available",
    "programs.talented.description": "Supporting outstanding Palestinian students across various academic fields, developing exceptional leaders who will drive innovation and progress in their communities.",
    "programs.talented.focus": "Program Focus",
    "programs.talented.features": "Key Features",
    "programs.talented.excellence": "Academic Excellence",
    "programs.talented.leadership": "Leadership Development",
    "programs.talented.fields": "Multiple Fields",
    "programs.talented.support": "Comprehensive Support",
    "programs.explore": "Explore All Programs",

    // Home page Your Path to Success section
    "journey.badge": "Student Journey",
    "journey.title": "Your Path to Success",
    "journey.subtitle": "From application to graduation, we provide comprehensive support at every step of your academic journey.",
    "journey.application.title": "Application",
    "journey.application.description": "Submit your application through our streamlined process. We review each application carefully to identify promising candidates.",
    "journey.application.form": "Online Application Form",
    "journey.application.documents": "Document Submission",
    "journey.application.screening": "Initial Screening",
    "journey.selection.title": "Selection",
    "journey.selection.description": "Our expert committee evaluates candidates based on academic excellence, leadership potential, and commitment to community.",
    "journey.selection.review": "Academic Review",
    "journey.selection.interview": "Interview Process",
    "journey.selection.final": "Final Selection",
    "journey.support.title": "Support",
    "journey.support.description": "Receive comprehensive support throughout your academic journey, including financial aid, mentorship, and career guidance.",
    "journey.support.financial": "Financial Support",
    "journey.support.mentoring": "Academic Mentoring",
    "journey.support.career": "Career Development",
    "journey.success.title": "Success",
    "journey.success.description": "Join our network of successful graduates who are making a difference in their communities and beyond.",
    "journey.success.graduation": "Graduation Support",
    "journey.success.alumni": "Alumni Network",
    "journey.success.opportunities": "Career Opportunities",
    "journey.start": "Start Your Journey",

    // Home page Call to Action section
    "cta.title": "Join Us in Empowering Palestinian Students",
    "cta.description": "Your support can make a lasting impact on the lives of talented Palestinian students. Together, we can build a brighter future through education.",
    "cta.button": "Support Our Cause",

    // Home page Partners section
    "partners.badge": "Our Partners",
    "partners.title": "Working Together for Change",
    "partners.subtitle": "We collaborate with leading institutions and organizations to provide comprehensive support to Palestinian students.",

    // Home page Contact section
    "contact.badge": "Get in Touch",
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions? Our team is here to help you with any inquiries about our programs and application process.",
    "contact.button": "Contact Our Team",

    // Stats section
    "stats.scholarships": "Scholarships Awarded",
    "stats.beneficiaries": "beneficiaries",
    "stats.countries": "Countries Reached",
    "stats.graduation": "Graduation Rate %",

    // Footer section
    "footer.description": "Empowering Palestinian students worldwide through educational opportunities, financial support, and academic resources.",
    "footer.programs.undergraduate": "Undergraduate Programs",
    "footer.programs.graduate": "Graduate Programs",
    "footer.programs.research": "Research Programs",
    "footer.about.mission": "Our Mission",
    "footer.about.team": "Team",
    "footer.about.partners": "Partners",

    // About page specific translations
    "about.page.indicator": "Who Are We",
    "about.purpose.badge": "Our Purpose",
    "about.purpose.title": "Mission & Vision",
    "about.purpose.subtitle": "Guided by our commitment to educational equity and empowerment for Palestinian students worldwide.",
    "about.mission.point1": "Provide scholarships to talented Palestinian students",
    "about.mission.point2": "Create educational opportunities through global partnerships",
    "about.mission.point3": "Support academic and professional development",
    "about.vision.point1": "A world where every Palestinian student has access to quality education",
    "about.vision.point2": "A global network of Palestinian scholars and professionals",
    "about.vision.point3": "Educational empowerment as a path to community development",
    "about.partners.badge": "Collaborations",
    "about.partners.title": "Our Partners",
    "about.partners.subtitle": "We collaborate with universities, educational institutions, and organizations worldwide to expand opportunities for Palestinian students.",
    "about.cta.title": "Join Our Mission",
    "about.cta.subtitle": "Whether you're a student looking for support, a potential partner, or someone who wants to contribute to our cause, we'd love to hear from you.",
    "about.cta.contact": "Contact Us",
    "about.cta.support": "Support Our Work",

    // Pulse of Life page translations
    "pulse.title": "Pulse of Life",
    "pulse.subtitle": "Medical Scholarship Program",
    "pulse.tagline": "🩺 The Health of Palestine... Our Responsibility 🏥",
    "pulse.stats.scholarships": "Scholarships",
    "pulse.stats.years": "Years",
    "pulse.stats.pillars": "Support Pillars",
    "pulse.about.title": "About the Program",
    "pulse.about.description": "is a bold national initiative launched by the Isnad Foundation, aiming to provide 1,000 full scholarships in medicine and health sciences to Palestinian students inside and outside Palestine—especially in rare and critical specializations. The program is designed to run over a period of 5 years.",
    "pulse.apply": "Apply for Pulse of Life Scholarship",
    "pulse.download.en": "Download Program (EN)",
    "pulse.download.ar": "تحميل البرنامج (AR)",
    "pulse.why.title": "Why Pulse of Life?",
    "pulse.why.shortage.title": "Shortage of Medical Personnel",
    "pulse.why.shortage.description": "There is a critical lack of qualified medical and healthcare professionals, which limits service delivery and reduces the quality of care in health institutions.",
    "pulse.why.specialized.title": "Lack of Specialized Fields",
    "pulse.why.specialized.description": "The local healthcare system suffers from a shortage of specialists in key medical fields, further straining the Ministry of Health and limiting advanced care options.",
    "pulse.why.capacity.title": "Shortage in Hospital Capacity",
    "pulse.why.capacity.description": "A lack of hospital beds and essential resources means many patients cannot receive timely care, leading to higher mortality rates and overwhelming existing facilities.",
    "pulse.why.infrastructure.title": "Poor Healthcare Infrastructure",
    "pulse.why.infrastructure.description": "Many medical devices are out of service, and essential resources to run healthcare facilities efficiently are missing, making it difficult to provide adequate care.",
    "pulse.why.occupation.title": "Impact of the Israeli Occupation",
    "pulse.why.occupation.description": "Since 2023, ongoing Israeli attacks have destroyed numerous health facilities, severely limiting the ability to deliver services and reducing the overall capacity of the healthcare system.",
    "pulse.goals.title": "Our Goals",
    "pulse.goals.train": "Train 1,000 students in medicine and health sciences through full scholarships.",
    "pulse.goals.support": "Support local healthcare by integrating graduates into the system.",
    "pulse.goals.reach": "Reach underserved areas through mobile clinics and awareness efforts.",
    "pulse.financial.title": "Pulse of Life Scholarship Financial Support",
    "pulse.financial.education.title": "Education Support",
    "pulse.financial.education.description": "Full coverage of medical education costs",
    "pulse.financial.education.amount": "$5,600",
    "pulse.financial.education.period": "per academic year",
    "pulse.financial.stipend.title": "Monthly Stipend",
    "pulse.financial.stipend.description": "Monthly living expenses support",
    "pulse.financial.stipend.amount": "$200",
    "pulse.financial.stipend.period": "monthly ($2,400/year)",
    "pulse.financial.technology.title": "Technology Grant",
    "pulse.financial.technology.description": "One-time device purchase support",
    "pulse.financial.technology.amount": "$300",
    "pulse.financial.technology.period": "one-time grant",
    "pulse.requirements.title": "Requirements",
    "pulse.requirements.nationality": "Palestinian Nationality",
    "pulse.requirements.average": "High School Average ≥ 90%",
    "pulse.requirements.gpa": "GPA 3.00+",
    "pulse.requirements.english": "English Proficiency Preferred",
    "pulse.fields.title": "Fields of Study",
    "pulse.fields.medicine": "Human Medicine",
    "pulse.fields.dentistry": "Dentistry",
    "pulse.fields.pharmacy": "Pharmacy",
    "pulse.fields.allied": "Allied Health Professions",
    "pulse.fields.nursing": "Nursing",
    "pulse.apply.now": "Apply Now",
    "pulse.contact.title": "Contact Us",
    "pulse.contact.description": "For more information, reach out to us:",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.about": "من نحن؟",
    "nav.news": "آخر الأخبار",
    "nav.programs": "برامجنا",
    "nav.success": "قصص النجاح",
    "nav.apply": "التقدم للمنح",
    "nav.activities": "الأنشطة السابقة",
    "nav.testimonials": "الشهادات",
    "nav.contact": "اتصل بنا",
    "nav.media": "الإعلام",
    "nav.media.success": "قصص النجاح",
    "nav.media.activities": "الأنشطة السابقة",
    "nav.media.testimonials": "الشهادات",
    "nav.donate": "تبرع الآن",
    "nav.donate.title": "ادعم قضيتنا",
    "nav.donate.desc": "ساعد الطلاب الفلسطينيين في تحقيق أحلامهم",

    "about.widgt": "القيم",
    "about.title":"قيمنا",
    "about.subtitle":"IFPPS",
    "about.identity": "الانتماء الوطني",
    "about.identity.desc": "نعمل انطلاقًا من التزامنا الراسخ بالقضية الفلسطينية، ونسعى جاهدين لترسيخ الهوية الوطنية في كل ما نقوم به",
    "about.identity2":"التميز الأكاديمي",
    "about.identity2.desc":"ندعم المواهب العلمية والأكاديمية، ونشجع على السعي الدائم نحو التميز والمعرفة",
    "about.identity3":"العدالة وتكافؤ الفرص",
    "about.identity3.desc":"نؤمن بضرورة توفير الفرص للمجتمع على أساس الكفاءة والجدارة، دون تمييز",
    "about.identity4":"الشفافية والنزاهة",
    "about.identity4.desc":"نؤدي عملنا بروح من الوضوح والمساءلة، محافظين على الثقة المتبادلة مع شركائنا",
    "about.identity5":"الاستدامة",
    "about.identity5.desc":"نخطط ونعمل بروح استشرافية تضمن أثرًا إيجابيًا طويل الأمد على المجتمع الفلسطيني",
    "about.identity6":"تمكين الشباب",
    "about.identity6.desc":"نؤمن بأهمية دعم وتمكين المواهب الأكاديمية الفلسطينية الشابة، فهم المحرك الأساسي لبناء المستقبل وتحقيق التنمية الوطنية المستدامة",
    "about.identity7":"المبادرة",
    "about.identity7.desc":"نسعى باستمرار لتحديد احتياجات الطلاب، وتقديم مشاريع تلبي هذه الاحتياجات، وتشجيعهم على إطلاق مبادرات مجتمعية",
    "about.cta":"من نحن",



    "hero.title": "تمكين الطلاب الفلسطينيين حول العالم",
    "hero.subtitle":
      "تقديم المنح الدراسية والمساعدة في القبول الجامعي والدعم الأكاديمي لمساعدة الطلاب الفلسطينيين على تحقيق أحلامهم التعليمية.",
    "hero.cta.apply": "التقدم للمنحة",
    "hero.cta.explore": "استكشاف البرامج",
    "about.hero.title": "من نحن؟",
    "about.hero.description": "صندوق الإسناد الفلسطيني هو كيان تنموي مستقل وغير ربحي، يهدف إلى دعم مسيرة التعليم العالي في فلسطين عبر الاستثمار في الطاقات الشبابية الأكاديمية. يركّز الصندوق على تقديم برامج ومبادرات تساهم في سد الفجوة بين مخرجات التعليم واحتياجات المجتمع، من خلال توفير منح دراسية، وتيسير الوصول إلى التخصصات ذات الأولوية الوطنية. كما يعمل على خلق شبكة معرفية تجمع بين الكفاءات الفلسطينية داخل الوطن وفي الشتات، ضمن رؤية تنموية شاملة",
    "about.mission.tag": "رسالتنا",
    "about.mission.title": "التمكين من خلال التعليم",
    "about.mission.text": "يُعنى صندوق الإسناد الفلسطيني بدعم الطلبة الفلسطينيين المتميزين لإكمال دراساتهم العليا في التخصصات الحيوية التي يحتاجها المجتمع الفلسطيني، من خلال تقديم منح دراسية موجهة. ويسعى الصندوق إلى تحقيق الربط الفعّال بين قطاع التعليم ومتطلبات التنمية الاقتصادية والاجتماعية في فلسطين. كما يعمل على تأسيس شبكة من الكفاءات الأكاديمية الفلسطينية داخل الوطن وخارجه، لدعم البحث العلمي والمساهمة في تطوير المؤسسات الوطنية. ويؤمن الصندوق بأهمية تعزيز دور الشباب في النشاط المجتمعي، عبر برامج تعليمية وتوعوية تهدف إلى ترسيخ مفاهيم التفاعل، والانسجام الاجتماعي، والانتماء الوطني",
    "about.vision.tag": "رؤيتنا",
    "about.vision.title": "بناء قادة المستقبل",
    "about.vision.text": "كفاءات أكاديمية فلسطينية شابة في المجالات التي يحتاجها المجتمع الفلسطيني والمساهمة الفعالة في بناء مستقبل مستدام وقوي للدولة الفلسطينية، مع التركيز على دعم الهوية الوطنية وتعزيز المشاركة المجتمعية",
    "about.foundation.tag": "هوية المؤسسة",
    "about.foundation.title": "قصتنا",
    "about.foundation.text1": "تأسس صندوق دعم الطلاب الفلسطينيين في عام 2015 في إسطنبول، تركيا، على يد مجموعة من المربين والمهنيين الذين أدركوا التحديات التي يواجهها الطلاب الفلسطينيون الساعون للحصول على فرص التعليم العالي.",
    "about.foundation.text2": "ما بدأ كمبادرة صغيرة لتقديم المنح الدراسية لعدد قليل من الطلاب نما ليصبح مؤسسة دعم شاملة ساعدت مئات الطلاب الفلسطينيين في الوصول إلى تعليم عالي الجودة في جميع أنحاء العالم.",
    "about.foundation.text3": "مؤسستنا مسجلة كمنظمة تعليمية غير ربحية في تركيا، تعمل بشفافية ومسؤولية كاملة تجاه المانحين والشركاء.",
    "about.team.tag": "الهيكل الإداري",
    "about.team.title": "فريقنا",
    "about.team.viewAll": "عرض الفريق بالكامل",
    "about.team.member1.name": "د. محمود عباس",
    "about.team.member1.title": "المدير التنفيذي",
    "about.team.member1.description": "أستاذ جامعي سابق مع أكثر من 20 عام من الخبرة في الإدارة التعليمية.",
    "about.team.member2.name": "د. ليلى خالد",
    "about.team.member2.title": "المدير الأكاديمي",
    "about.team.member2.description": "متخصصة في سياسة التعليم الدولي وبرامج إرشاد الطلاب.",
    "about.team.member3.name": "عمر فاروق",
    "about.team.member3.title": "المدير المالي",
    "about.team.member3.description": "خبير في الإدارة المالية للمنظمات غير الربحية وإدارة صناديق المنح الدراسية.",

    "work.badget":"التعليم، التمكين، التواصل",
    "work.title":"مجالات عمل المؤسسة",
    "work.subtitle": "تمكين الشباب الفلسطيني من خلال التعليم والابتكار والتواصل",
    "card1.title":"المنح الدراسية والدعم الأكاديمي",
    "Card1.desc":"توفير منح دراسية للشباب الفلسطيني في تخصصات يحتاجها سوق العمل والمجتمع داخل فلسطين وخارجها.",
    "Card2.title":"بناء القدرات والتطوير المهني",
    "Card2.desc":"تنظيم ورش عمل تدريبية وبرامج تطوير مهني واستشارات لإعداد الشباب لسوق العمل وتعزيز مهاراتهم القيادية والتقنية.",
    "Card3.title":"البحث العلمي والمساهمة المعرفية",
    "Card3.desc":" تمويل وتشجيع البحوث التطبيقية المتعلقة بالتنمية الوطنية، وإقامة شراكات مع الجامعات ومراكز البحوث.",
    "Card4.title":"تعزيز الهوية الوطنية والمشاركة المجتمعية",
    "Card4.desc":"تنفيذ برامج ثقافية وتعليمية وتوعوية تهدف إلى ترسيخ القيم الوطنية وتفعيل دور الشباب في الحياة العامة.",
    "Card5.title": "بناء شبكة كفاءات فلسطينية",
    "Card5.desc": "ربط الكفاءات الفلسطينية المحلية بالخارج، وتفعيل جسور التواصل بين الأكاديميين والباحثين والمؤسسات ذات العلاقة.",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.programs": "البرامج",
    "footer.about": "عن المؤسسة",
    "footer.contact": "اتصل بنا",

    "donate.hero.title": "دعم الطلاب الفلسطينيين",
    "donate.hero.subtitle": "تبرعك يساعد في توفير المنح الدراسية والدعم التعليمي والفرص للطلاب الفلسطينيين حول العالم.",
    "donate.form.title": "تبرع الآن",
    "donate.form.amount": "اختر المبلغ",
    "donate.form.custom": "مبلغ مخصص",
    "donate.form.payment": "طريقة الدفع",
    "donate.form.card": "بطاقة ائتمان/خصم",
    "donate.form.bank": "تحويل بنكي",
    "donate.form.button": "تبرع الآن",
    "donate.trust.secure": "دفع آمن",
    "donate.trust.tax": "معفى من الضرائب",
    "donate.impact.title": "تأثيرك",
    "donate.impact.students": "طالب مدعوم",
    "donate.impact.scholarships": "منحة مقدمة",
    "donate.impact.countries": "دولة مستفيدة",
    "donate.faq.title": "الأسئلة الشائعة",
    "donate.faq.use": "كيف سيتم استخدام تبرعي؟",
    "donate.faq.use.answer": "يذهب تبرعك مباشرة لدعم الطلاب الفلسطينيين من خلال المنح الدراسية والبرامج التعليمية والدعم الأكاديمي. نحن نضمن الشفافية في توزيع الأموال ونقدم تحديثات منتظمة عن تأثير مساهمتك.",
    "donate.faq.tax": "هل تبرعي معفى من الضرائب؟",
    "donate.faq.tax.answer": "نعم، جميع التبرعات لصندوق الإسناد الفلسطيني معفاة من الضرائب. نحن نقدم إيصالات التبرع لجميع المساهمات، والتي يمكن استخدامها للأغراض الضريبية في الولايات القضائية المعمول بها.",
    "donate.faq.recurring": "هل يمكنني تقديم تبرع متكرر؟",
    "donate.faq.recurring.answer": "نعم، نقدم خيارات التبرع المتكرر شهرياً وربع سنوياً وسنوياً. يمكنك إعداد وإدارة تبرعاتك المتكررة من خلال نظام الدفع الآمن لدينا.",
    "donate.faq.track": "كيف يمكنني متابعة تأثير تبرعي؟",
    "donate.faq.track.answer": "نقدم تحديثات منتظمة من خلال النشرة الإخبارية وتقارير التأثير السنوية. يمكنك أيضاً متابعة قصص النجاح وشهادات الطلاب على موقعنا الإلكتروني وقنوات التواصل الاجتماعي.",
    "donate.form.type": "اختر نوع التبرع",
    "donate.form.general": "تبرع عام",
    "donate.form.specific": "تبرع لبرنامج محدد",
    "donate.form.select_program": "اختر البرنامج",
    "donate.form.choose_program": "اختر برنامجاً",
    "donate.form.distribution": "التوزيع المالي",
    "donate.form.distribution_desc": "سيتم توزيع تبرعك كالتالي:",
    "donate.programs.scholarships": "برنامج المنح الدراسية",
    "donate.programs.research": "البحث والتطوير",
    "donate.programs.capacity": "بناء القدرات",
    "donate.programs.pulse": "منحة نبض الحياة",
    "donate.programs.pulse.desc": "منح دراسية كاملة في الطب والعلوم الصحية للطلاب الفلسطينيين. دعم 1,000 طالب على مدى 5 سنوات.",
    "donate.programs.talented": "الطلاب الفلسطينيون الموهوبون",
    "donate.programs.talented.desc": "دعم الطلاب الفلسطينيين المتميزين في مختلف المجالات الأكاديمية. 1,000 منحة لقادة استثنائيين.",
    "donate.programs.sustainability": "الاستدامة",
    "donate.programs.sustainability.desc": "200 منحة في هندسة الطاقة والزراعة لمستقبل فلسطين الأخضر.",
    "donate.programs.justice": "العدالة لفلسطين",
    "donate.programs.justice.desc": "200 منحة في العلوم السياسية والعلاقات الدولية للدعوة العالمية.",
    "donate.programs.ibn-khaldun": "ابن خلدون",
    "donate.programs.ibn-khaldun.desc": "200 منحة في علم الاجتماع وعلم النفس لفهم المجتمع الفلسطيني.",
    "donate.programs.duration": "مدة البرنامج",
    "donate.programs.focus": "مجال التخصص",

    // Sustainability Scholarship Arabic translations
    "sustainability.title": "برنامج منحة الاستدامة",
    "sustainability.subtitle": "نحو السيادة العالمية ومجتمع يقود تنميته الذاتية",
    "sustainability.scholarships": "منح دراسية",
    "sustainability.years": "سنوات",
    "sustainability.majors": "تخصصات",
    "sustainability.about.title": "حول البرنامج",
    "sustainability.about.desc": "برنامج منحة الاستدامة للدراسات العليا هو مبادرة وطنية من مؤسسة إسناد لدعم الطلاب الفلسطينيين. يهدف إلى تأهيل المواهب الفلسطينية في المجالات الحيوية بما في ذلك الطاقة المستدامة والزراعة والموارد الطبيعية، لتحقيق السيادة الوطنية في الطاقة والغذاء، وتعزيز التنمية المستدامة في فلسطين.",
    "sustainability.why.title": "لماذا منحة الاستدامة؟",
    "sustainability.why.energy.title": "الاعتماد الكبير على الطاقة المستوردة",
    "sustainability.why.energy.desc": "تعتمد فلسطين على الطاقة المستوردة بنسبة 87.4% من احتياجاتها، مما يجعلها عرضة للأزمات ويؤثر على التنمية الاقتصادية والاجتماعية",
    "sustainability.why.renewable.title": "مساهمة منخفضة للطاقة المتجددة",
    "sustainability.why.renewable.desc": "رغم الإمكانات الطبيعية الكبيرة لفلسطين في الطاقة المتجددة، إلا أن مساهمتها في الإنتاج المحلي لا تتجاوز 4.7%",
    "sustainability.why.agriculture.title": "تحديات القطاع الزراعي",
    "sustainability.why.agriculture.desc": "يواجه القطاع الزراعي الفلسطيني تحديات كبيرة تتعلق بندرة المياه وتراجع المساحات المزروعة وضعف استخدام التقنيات الحديثة في الإنتاج النباتي والحيواني والغذائي",
    "sustainability.why.occupation.title": "تأثير الاحتلال على الموارد الطبيعية",
    "sustainability.why.occupation.desc": "يستنزف الاحتلال الموارد الطبيعية الفلسطينية ويحد من قدرة الفلسطينيين على الاستثمار فيها",
    "sustainability.why.programs.title": "نقص البرامج الأكاديمية المتخصصة",
    "sustainability.why.programs.desc": "هناك قلة في البرامج الأكاديمية المتخصصة في مجالات الطاقة والزراعة والموارد الطبيعية",
    "sustainability.why.research.title": "نقص البحث العلمي التطبيقي",
    "sustainability.why.research.desc": "هناك نقص في البحوث التطبيقية التي تساهم في تطوير حلول عملية للمشاكل المحلية",
    "sustainability.objectives.title": "أهدافنا",
    "sustainability.objectives.subtitle": "تمكين جيل جديد لقيادة مستقبل فلسطين المستدام, إليكم ما نسعى إليه",
    "sustainability.objectives.scholarships.title": "200 منحة دراسية كاملة",
    "sustainability.objectives.scholarships": "منح 200 منحة دراسية كاملة للطلاب الفلسطينيين المتميزين في الطاقة والزراعة والموارد الطبيعية - تغذية الموجة القادمة من صناع التغيير",
    "sustainability.objectives.research.title": "البحث التطبيقي",
    "sustainability.objectives.research": "إشعال البحث العلمي التطبيقي الذي يقدم حلولاً حقيقية لفلسطين أكثر خضرة ومرونة",
    "sustainability.objectives.knowledge.title": "المعرفة والابتكار",
    "sustainability.objectives.knowledge": "تعزيز المعرفة والابتكار الفلسطيني، وربط البحث بالأولويات الوطنية والتأثير الواقعي",
    "sustainability.objectives.leaders.title": "قادة المستقبل",
    "sustainability.objectives.leaders": "إلهام وتخريج قادة مستعدين لقيادة التنمية المستدامة والتغيير الإيجابي في جميع أنحاء فلسطين",
    "sustainability.financial.title": "الدعم المالي",
    "sustainability.financial.tuition.title": "الرسوم الدراسية السنوية",
    "sustainability.financial.tuition.desc": "تغطي المنحة الرسوم الدراسية السنوية",
    "sustainability.financial.tuition.amount": "3,000 دولار",
    "sustainability.financial.tuition.period": "لكل سنة أكاديمية",
    "sustainability.financial.living.title": "دعم المعيشة السنوي",
    "sustainability.financial.living.desc": "يحصل الطلاب على راتب شهري للمعيشة",
    "sustainability.financial.living.amount": "200 دولار",
    "sustainability.financial.living.period": "شهرياً (2,400 دولار/سنة)",
    "sustainability.financial.housing.title": "دعم السكن",
    "sustainability.financial.housing.desc": "إذا لزم الأمر، توفر المنحة دعماً سنوياً للسكن",
    "sustainability.financial.housing.amount": "2,400 دولار",
    "sustainability.financial.housing.period": "سنوياً",
    "sustainability.contact.title": "اتصل بنا",
    "sustainability.contact.desc": " : لمزيد من المعلومات، يرجى الاتصال بنا",
    "sustainability.apply": "تقدم الآن",
    "sustainability.download.en": "تحميل البرنامج (EN)",
    "sustainability.download.ar": "تحميل البرنامج (AR)",

    // Palestinian Talented Scholarship Arabic translations
    "talented.title": "منحة  الموهوب  الفلسطيني",
    "talented.subtitle": "برنامج منحة التميز",
    "talented.tagline": "🌟 دعم المواهب الفلسطينية: مسؤوليتنا الجماعية ⭐",
    "talented.scholarships": "منح دراسية",
    "talented.areas": "مجالات الدعم",
    "talented.pillars": "الركائز المالية",
    "talented.about.title": "حول برنامج التميز",
    "talented.about.desc": "برنامج منحة الطالب الفلسطيني الموهوب هو مبادرة وطنية أطلقتها مؤسسة إسناد، تقدم 1,000 منحة دراسية للطلاب المتميزين داخل فلسطين في مختلف المجالات الأكاديمية. البرنامج مصمم لتطوير قادة استثنائيين في مختلف المجالات الأكاديمية وتمكين الشباب من تحقيق إمكاناتهم الكاملة وخدمة المجتمع.",
    "talented.apply": "تقدم لمنحة الموهوب الفلسطيني",
    "talented.download.en": "تحميل البرنامج (EN)",
    "talented.download.ar": "تحميل البرنامج (AR)",
    "talented.why.title": "لماذا دعم المواهب الفلسطينية؟",
    "talented.why.programs.title": "نقص البرامج المتخصصة",
    "talented.why.programs.desc": "لا توجد برامج وطنية شاملة تدعم الطلاب المتميزين وتساعدهم على تحقيق إمكاناتهم في التميز الأكاديمي والمشاريع الابتكارية",
    "talented.why.environment.title": "الحرمان من البيئة التعليمية المناسبة",
    "talented.why.environment.desc": "بسبب نقص البنية التحتية التعليمية في فلسطين، العديد من الطلاب غير قادرين على الوصول إلى الموارد والأدوات التي يحتاجونها للتطوير والنجاح الأكاديمي",
    "talented.why.brain.title": "هجرة الأدمغة وفقدان المواهب المبكر",
    "talented.why.brain.desc": "غياب آليات الدعم المبكر للطلاب الاستثنائيين يؤدي إلى فقدان العديد من الأفراد الموهوبين الذين كان بإمكانهم المساهمة في مجتمعاتهم",
    "talented.why.development.title": "نقص برامج تطوير المواهب",
    "talented.why.development.desc": "الطلاب الفلسطينيون الموهوبون غالباً ما يفتقرون إلى الوصول للبرامج المتخصصة التي يمكنها رعاية مواهبهم ومساعدتهم على تطوير مهاراتهم والمساهمة في المجتمع",
    "talented.why.occupation.title": "ممارسات الاحتلال تؤثر سلباً على الرفاهية والفرص التعليمية",
    "talented.why.occupation.desc": "الاحتلال المستمر له تأثير سلبي على الرفاهية النفسية والتعليمية للطلاب. الضغط المستمر وعدم اليقين يجعل من الصعب التركيز على الأهداف التعليمية",
    "talented.why.economic.title": "الظروف الاقتصادية الصعبة تحد من الوصول للتعليم العالي",
    "talented.why.economic.desc": "القيود المالية والظروف الاقتصادية الصعبة تمنع العديد من الطلاب الفلسطينيين من متابعة التعليم العالي وتحقيق أحلامهم",
    "talented.why.achievement.title": "الإنجاز المتميز صعب التحقيق بدون دعم هامشي",
    "talented.why.achievement.desc": "لتحقيق نتائج متميزة، يحتاج الطلاب إلى دعم شامل يشمل المساعدة المالية والإرشاد والوصول إلى الموارد التعليمية المتقدمة",
    "talented.why.infrastructure.title": "وصول محدود للبنية التحتية التعليمية عالية الجودة",
    "talented.why.infrastructure.desc": "العديد من الطلاب الفلسطينيين يفتقرون إلى الوصول للمرافق التعليمية الحديثة والمختبرات المتقدمة والتكنولوجيا المتطورة الضرورية للتميز الأكاديمي والابتكار",
    "talented.goals.title": "أهدافنا",
    "talented.goals.scholarships": "منح 1,000 منحة دراسية كاملة للطلاب الفلسطينيين المتميزين",
    "talented.goals.leaders": "تطوير قادة استثنائيين في مختلف المجالات الأكاديمية",
    "talented.goals.potential": "تمكين الشباب من تحقيق إمكاناتهم الكاملة وخدمة المجتمع",
    "talented.financial.title": "الدعم المالي لمنحة التميز",
    "talented.financial.academic.title": "التميز الأكاديمي",
    "talented.financial.academic.desc": "تغطية كاملة لتكاليف برنامج التميز الأكاديمي",
    "talented.financial.academic.amount": "2,500 دولار",
    "talented.financial.academic.period": "لكل سنة أكاديمية",
    "talented.financial.stipend.title": "الراتب الشهري",
    "talented.financial.stipend.desc": "دعم مصاريف المعيشة الشهرية",
    "talented.financial.stipend.amount": "200 دولار",
    "talented.financial.stipend.period": "شهرياً (2,400 دولار/سنة)",
    "talented.financial.technology.title": "منحة التكنولوجيا",
    "talented.financial.technology.desc": "دعم لمرة واحدة لشراء الأجهزة",
    "talented.financial.technology.amount": "300 دولار",
    "talented.financial.technology.period": "منحة لمرة واحدة",
    "talented.requirements.title": "المتطلبات",
    "talented.requirements.nationality": "الجنسية الفلسطينية",
    "talented.requirements.average": "معدل الثانوية العامة ≥ 90%",
    "talented.requirements.gpa": "معدل تراكمي 3.00+",
    "talented.requirements.english": "إجادة اللغة الإنجليزية مفضلة",
    "talented.fields.title": "مجالات الدراسة",
    "talented.fields.business": "إدارة الأعمال",
    "talented.fields.engineering": "الهندسة",
    "talented.fields.education": "التعليم",
    "talented.fields.social": "العلوم الاجتماعية",
    "talented.fields.computer": "علوم الحاسوب",
    "talented.fields.international": "العلاقات الدولية",
    "talented.fields.economics": "الاقتصاد",
    "talented.fields.law": "القانون",
    "talented.fields.psychology": "علم النفس",
    "talented.fields.media": "الإعلام والاتصالات",
    "talented.contact.title": "اتصل بنا",
    "talented.contact.desc": "لمزيد من المعلومات، تواصل معنا:",
    "talented.apply.now": "تقدم الآن",

    // Home page News & Announcements section Arabic
    "news.badge": "آخر التحديثات",
    "news.title": "الأخبار والإعلانات",
    "news.subtitle": "ابق على اطلاع بآخر أخبارنا وتحديثاتنا والإعلانات المهمة من المؤسسة",
    "news.viewAll": "عرض جميع الأخبار",

    // Home page Our Programs section Arabic
    "programs.badge": "برامج المنح الدراسية",
    "programs.title": "برامجنا",
    "programs.subtitle": "تمكين الطلاب الفلسطينيين من خلال برامج المنح الدراسية المتخصصة",
    "programs.pulse.title": "منحة نبض الحياة",
    "programs.pulse.category": "الطب والعلوم الصحية",
    "programs.pulse.scholarships": " ١,٠٠٠ منحة دراسية على مدى ٥ سنوات",
    "programs.pulse.description": "مبادرة وطنية جريئة تقدم منحاً دراسية كاملة في الطب والعلوم الصحية، مع التركيز على التخصصات النادرة والحرجة لتعزيز الرعاية الصحية في فلسطين",
    "programs.pulse.focus": "تركيز البرنامج",
    "programs.pulse.features": "الميزات الرئيسية",
    "programs.pulse.medical": "التعليم الطبي",
    "programs.pulse.innovation": "الابتكار في الرعاية الصحية",
    "programs.pulse.full": "منح دراسية كاملة",
    "programs.pulse.years": "برنامج 5 سنوات",
    "programs.talented.title": "منحة الموهوب الفلسطيني",
    "programs.talented.category": "منحة التميز",
    "programs.talented.scholarships": "١,٠٠٠ منحة دراسية متاحة",
    "programs.talented.description": "دعم الطلاب الفلسطينيين المتميزين في مختلف المجالات الأكاديمية، وتطوير قادة استثنائيين سيقودون الابتكار والتقدم في مجتمعاتهم",
    "programs.talented.focus": "تركيز البرنامج",
    "programs.talented.features": "الميزات الرئيسية",
    "programs.talented.excellence": "التميز الأكاديمي",
    "programs.talented.leadership": "تطوير القيادة",
    "programs.talented.fields": "مجالات متعددة",
    "programs.talented.support": "دعم شامل",
    "programs.explore": "استكشف جميع البرامج",

    // Home page Your Path to Success section Arabic
    "journey.badge": "رحلة الطالب",
    "journey.title": "طريقك إلى النجاح",
    "journey.subtitle": "من التقديم إلى التخرج، نحن نقدم دعماً شاملاً في كل خطوة من رحلتك الأكاديمية",
    "journey.application.title": "التقديم",
    "journey.application.description": "قدم طلبك من خلال عمليتنا المبسطة. نحن نراجع كل طلب بعناية لتحديد المرشحين الواعدين",
    "journey.application.form": "نموذج التقديم الإلكتروني",
    "journey.application.documents": "تقديم الوثائق",
    "journey.application.screening": "الفحص الأولي",
    "journey.selection.title": "الاختيار",
    "journey.selection.description": "تقوم لجنتنا الخبيرة بتقييم المرشحين بناءً على التميز الأكاديمي والإمكانات القيادية والالتزام بالمجتمع",
    "journey.selection.review": "المراجعة الأكاديمية",
    "journey.selection.interview": "عملية المقابلة",
    "journey.selection.final": "الاختيار النهائي",
    "journey.support.title": "الدعم",
    "journey.support.description": "احصل على دعم شامل طوال رحلتك الأكاديمية، بما في ذلك المساعدة المالية والإرشاد والتوجيه المهني",
    "journey.support.financial": "الدعم المالي",
    "journey.support.mentoring": "الإرشاد الأكاديمي",
    "journey.support.career": "التطوير المهني",
    "journey.success.title": "النجاح",
    "journey.success.description": "انضم إلى شبكة خريجينا الناجحين الذين يحدثون فرقاً في مجتمعاتهم وما بعدها",
    "journey.success.graduation": "دعم التخرج",
    "journey.success.alumni": "شبكة الخريجين",
    "journey.success.opportunities": "الفرص المهنية",
    "journey.start": "ابدأ رحلتك",

    // Home page Call to Action section Arabic
    "cta.title": "انضم إلينا في تمكين الطلاب الفلسطينيين",
    "cta.description": "يمكن لدعمك أن يحدث تأثيراً دائماً في حياة الطلاب الفلسطينيين الموهوبين. معاً، يمكننا بناء مستقبل أكثر إشراقاً من خلال التعليم",
    "cta.button": "ادعم قضيتنا",

    // Home page Partners section Arabic
    "partners.badge": "شركاؤنا",
    "partners.title": "العمل معاً من أجل التغيير",
    "partners.subtitle": "نحن نتعاون مع المؤسسات والمنظمات الرائدة لتقديم دعم شامل للطلاب الفلسطينيين",

    // Home page Contact section Arabic
    "contact.badge": "تواصل معنا",
    "contact.title": "اتصل بنا",
    "contact.subtitle": "هل لديك أسئلة؟ فريقنا هنا لمساعدتك في أي استفسارات حول برامجنا وعملية التقديم",
    "contact.button": "تواصل مع فريقنا",

    // Stats section Arabic
    "stats.scholarships": "منح دراسية مقدمة",
    "stats.beneficiaries": "مستفيد",
    "stats.countries": "دول مستفيدة",
    "stats.graduation": "معدل التخرج %",

    // Footer section Arabic
    "footer.description": "تمكين الطلاب الفلسطينيين حول العالم من خلال الفرص التعليمية والدعم المالي والموارد الأكاديمية",
    "footer.programs.undergraduate": "برامج البكالوريوس",
    "footer.programs.graduate": "برامج الدراسات العليا",
    "footer.programs.research": "برامج البحث",
    "footer.about.mission": "رسالتنا",
    "footer.about.team": "الفريق",
    "footer.about.partners": "الشركاء",

    // About page specific translations Arabic
    "about.page.indicator": "من نحن",
    "about.purpose.badge": "هدفنا",
    "about.purpose.title": "الرسالة والرؤية",
    "about.purpose.subtitle": "مسترشدين بالتزامنا بالعدالة التعليمية وتمكين الطلاب الفلسطينيين حول العالم",
    "about.mission.point1": "تقديم منح دراسية للطلاب الفلسطينيين الموهوبين",
    "about.mission.point2": "خلق فرص تعليمية من خلال الشراكات العالمية",
    "about.mission.point3": "دعم التطوير الأكاديمي والمهني",
    "about.vision.point1": "عالم يحصل فيه كل طالب فلسطيني على تعليم عالي الجودة",
    "about.vision.point2": "شبكة عالمية من الأكاديميين والمهنيين الفلسطينيين",
    "about.vision.point3": "التمكين التعليمي كطريق لتنمية المجتمع",
    "about.partners.badge": "التعاون",
    "about.partners.title": "شركاؤنا",
    "about.partners.subtitle": "نحن نتعاون مع الجامعات والمؤسسات التعليمية والمنظمات حول العالم لتوسيع الفرص للطلاب الفلسطينيين",
    "about.cta.title": "انضم إلى مهمتنا",
    "about.cta.subtitle": "سواء كنت طالباً تبحث عن الدعم، أو شريكاً محتملاً، أو شخصاً يريد المساهمة في قضيتنا، نحن نحب أن نسمع منك",
    "about.cta.contact": "اتصل بنا",
    "about.cta.support": "ادعم عملنا",

    // Pulse of Life page translations Arabic
    "pulse.title": "منحة نبض الحياة",
    "pulse.subtitle": "برنامج المنح الطبية",
    "pulse.tagline": "🩺 صحة فلسطين... مسؤوليتنا 🏥",
    "pulse.stats.scholarships": "منحة دراسية",
    "pulse.stats.years": "سنوات",
    "pulse.stats.pillars": "ركائز الدعم",
    "pulse.about.title": "عن البرنامج",
    "pulse.about.description": "هي مبادرة وطنية جريئة أطلقتها مؤسسة الإسناد، تهدف إلى تقديم 1,000 منحة دراسية كاملة في الطب والعلوم الصحية للطلاب الفلسطينيين داخل وخارج فلسطين—خاصة في التخصصات النادرة والحرجة. البرنامج مصمم ليعمل على مدى فترة 5 سنوات",
    "pulse.apply": "تقدم للمنحة نبض الحياة",
    "pulse.download.en": "تحميل البرنامج (EN)",
    "pulse.download.ar": "تحميل البرنامج (AR)",
    "pulse.why.title": "لماذا نبض الحياة؟",
    "pulse.why.shortage.title": "نقص في الكوادر الطبية",
    "pulse.why.shortage.description": "هناك نقص حاد في المهنيين الطبيين والصحيين المؤهلين، مما يحد من تقديم الخدمات ويقلل من جودة الرعاية في المؤسسات الصحية",
    "pulse.why.specialized.title": "نقص في المجالات المتخصصة",
    "pulse.why.specialized.description": "يعاني النظام الصحي المحلي من نقص في المتخصصين في المجالات الطبية الرئيسية، مما يزيد الضغط على وزارة الصحة ويحد من خيارات الرعاية المتقدمة",
    "pulse.why.capacity.title": "نقص في السعة الاستيعابية للمستشفيات",
    "pulse.why.capacity.description": "نقص في أسرة المستشفيات والموارد الأساسية يعني أن العديد من المرضى لا يمكنهم الحصول على الرعاية في الوقت المناسب، مما يؤدي إلى ارتفاع معدلات الوفيات وإرهاق المرافق الموجودة.",
    "pulse.why.infrastructure.title": "ضعف البنية التحتية للرعاية الصحية",
    "pulse.why.infrastructure.description": "العديد من الأجهزة الطبية خارج الخدمة، والموارد الأساسية لتشغيل المرافق الصحية بكفاءة مفقودة، مما يجعل من الصعب تقديم الرعاية المناسبة",
    "pulse.why.occupation.title": "تأثير الاحتلال الإسرائيلي",
    "pulse.why.occupation.description": "منذ عام 2023، دمرت الهجمات الإسرائيلية المستمرة العديد من المرافق الصحية، مما حد بشدة من القدرة على تقديم الخدمات وقلل من القدرة الإجمالية للنظام الصحي",
    "pulse.goals.title": "أهدافنا",
    "pulse.goals.train": "تدريب 1,000 طالب في الطب والعلوم الصحية من خلال منح دراسية كاملة",
    "pulse.goals.support": "دعم الرعاية الصحية المحلية من خلال دمج الخريجين في النظام",
    "pulse.goals.reach": "الوصول إلى المناطق المحرومة من خلال العيادات المتنقلة وجهود التوعية",
    "pulse.financial.title": "الدعم المالي لمنحة نبض الحياة",
    "pulse.financial.education.title": "دعم التعليم",
    "pulse.financial.education.description": "تغطية كاملة لتكاليف التعليم الطبي",
    "pulse.financial.education.amount": "$5,600",
    "pulse.financial.education.period": "لكل سنة أكاديمية",
    "pulse.financial.stipend.title": "راتب شهري",
    "pulse.financial.stipend.description": "دعم مصاريف المعيشة الشهرية",
    "pulse.financial.stipend.amount": "$200",
    "pulse.financial.stipend.period": "شهرياً ($2,400/سنة)",
    "pulse.financial.technology.title": "منحة التكنولوجيا",
    "pulse.financial.technology.description": "دعم لمرة واحدة لشراء الأجهزة",
    "pulse.financial.technology.amount": "$300",
    "pulse.financial.technology.period": "منحة لمرة واحدة",
    "pulse.requirements.title": "المتطلبات",
    "pulse.requirements.nationality": "الجنسية الفلسطينية",
    "pulse.requirements.average": "معدل الثانوية العامة ≥ 90%",
    "pulse.requirements.gpa": "معدل تراكمي 3.00+",
    "pulse.requirements.english": "إجادة اللغة الإنجليزية مفضلة",
    "pulse.fields.title": "مجالات الدراسة",
    "pulse.fields.medicine": "الطب البشري",
    "pulse.fields.dentistry": "طب الأسنان",
    "pulse.fields.pharmacy": "الصيدلة",
    "pulse.fields.allied": "المهن الصحية المساعدة",
    "pulse.fields.nursing": "التمريض",
    "pulse.apply.now": "تقدم الآن",
    "pulse.contact.title": "اتصل بنا",
    "pulse.contact.description": ":لمزيد من المعلومات، تواصل معنا",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "ar"].includes(savedLanguage)) {
      setLanguageState(savedLanguage)
      document.documentElement.lang = savedLanguage
      document.documentElement.dir = "ltr"
    } else {
      // Set default to Arabic if no saved language
      document.documentElement.lang = "ar"
      document.documentElement.dir = "ltr"
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
    document.documentElement.lang = lang
    document.documentElement.dir = "ltr"
  }

  const t = (key: string) => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

