"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "en" | "ar"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string | string[]
}

const translations = {
  en: {
    "news.latest.pulseOfLifeDisbursement.title": "Disbursements of the first phase of the Pulse of Life program have begun in Türkiye",
    "news.latest.pulseOfLifeDisbursement.excerpt": "The Isnad Foundation for Palestinian Student Support announced the commencement of disbursing scholarships to students benefiting from the first phase of the Nabd Al-Hayat program, starting May 1, 2025, in partnership with and with the generous support of the Turkish National Youth Association (MGV - Milli Gençlik Vakfı).",
    "news.latest.pulseOfLifeDisbursement.category": "Scholarships",



    "nav.home": "Home",
    "nav.about": "About",
    "nav.programs": "Our Programs",
    "nav.programs.undergraduate": "Undergraduate Scholarships",
    "nav.programs.graduate": "Graduate Scholarships",
    "nav.donate": "Donate",
    "nav.contact": "Contact",

    "nav.news": "Latest News",
    "nav.activities": "Previous Activities",
    "nav.testimonials": "Testimonials",
    "nav.media": "Media",
    "nav.media.success": "Success Stories",
    "nav.media.activities": "Previous Activities",
    "nav.media.testimonials": "What They Say About Us",
    "nav.educational.environment": "Educational Environment",

    "hero.title": "Empowering Palestinian Students Worldwide",
    "hero.subtitle":
      "Providing scholarships, university admissions assistance, and academic support to help Palestinian students achieve their educational dreams.",
    "hero.cta.apply": "Apply for Scholarship",
    "hero.cta.explore": "Explore Programs",


    "about.widgt": "Values",
    "about.title":"Our Values",
    "about.subtitle":"IFPPS",
    "about.identity": "National Belonging",
    "about.identity.desc": "We operate from a deep commitment to the Palestinian cause, striving to instill national identity in everything we do.",
    "about.identity2":"Academic Excellence",
    "about.identity2.desc":"We support scientific and academic talent and encourage the continuous pursuit of excellence and knowledge",
    "about.identity3":"Justice and Equal Opportunity",
    "about.identity3.desc":"We believe in the necessity of providing opportunities to society based on competence and merit, without discrimination.",
    "about.identity4":"Transparency and Integrity",
    "about.identity4.desc":"We conduct our work with a spirit of clarity and accountability, maintaining mutual trust with our partners.",
    "about.identity5":"Sustainability",
    "about.identity5.desc":"We plan and operate with a forward-looking spirit that ensures a long-term positive impact on Palestinian society.",
    "about.identity6":"Youth Empowerment",
    "about.identity6.desc":"We believe in the importance of supporting and empowering young Palestinian academic talent, as they are the primary engine for building the future and achieving sustainable national development.",
    "about.identity7":"Initiative",
    "about.identity7.desc":"We constantly strive to identify student needs, present projects that meet these needs, and encourage students to launch community initiatives.",
    "about.cta":"About Us",

    "about.hero.title": "Who Are We?",
    "about.hero.description": "The Palestinian Support Fund is an independent, non-profit development entity that aims to support higher education in Palestine by investing in the potential of young academics. The Fund focuses on providing programs and initiatives that contribute to bridging the gap between educational outcomes and community needs by providing scholarships and facilitating access to nationally prioritized majors. It also works to create a knowledge network that brings together Palestinian talents within the country and abroad, within a comprehensive development vision.",
    "about.mission.tag": "Our Mission",
    "about.mission.title": "Empowering Through Education",
    "about.mission.text": "To enhance the academic competencies of young Palestinian professionals in various disciplines needed by Palestinian society, enabling them to play a pivotal and effective role in building a sustainable, prosperous, and strong future for the Palestinian state.",
    "about.vision.tag": "Our Vision",
    "about.vision.title": "Building Future Leaders",
    "about.vision.text": "The Isnad Foundation for Palestinian Student Support believes in the importance of enhancing the role of youth in community activities through educational and awareness programs that aim to consolidate the concepts of interaction, social harmony, and national belonging.",
    "about.foundation.tag": "Foundation Identity",
    "about.foundation.title": "Our Story",
    "about.foundation.text1": "Established in 2015 in Istanbul, Turkey, the Isnad Foundation was founded by a group of educators and professionals who recognized the challenges faced by Palestinian students seeking higher education opportunities.",
    "about.foundation.text2": "What began as a small initiative providing scholarships to a handful of students has grown into a comprehensive support organization that has helped hundreds of Palestinian students access quality education across the globe.",
    "about.foundation.text3": "Our foundation is registered as a non-profit educational organization in Turkey, operating with full transparency and accountability to our donors and partners.",
    "about.team.tag": "Administrative Structure",
    "about.team.title": "Our Team",
    "about.team.viewAll": "View Full Team",
    "about.team.member1.name": "Dr. Mahmoud Abbas",
    "about.team.member1.title": "Executive Director",
    "about.team.member1.description": "Former university professor with 20+ years of experience in educational administration.",
    "about.team.member2.name": "Dr. Layla Khalid",
    "about.team.member2.title": "Academic Director",
    "about.team.member2.description": "Specializes in international education policy and student mentorship programs.",
    "about.team.member3.name": "Omar Farooq",
    "about.team.member3.title": "Financial Director",
    "about.team.member3.description": "Expert in non-profit financial management and scholarship fund administration.",

    "work.badget":"Educate. Empower. Connect.",
    "work.title":"The Foundation's areas of work",
    "work.subtitle":"Empowering Palestinian Youth Through Education, Innovation, and Connection",
    "card1.title":"Scholarships and Academic Support",
    "Card1.desc":"Providing scholarships to Palestinian youth in specializations needed by the labor market and society inside and outside Palestine.",
    "Card2.title":"Capacity Building and Professional Development",
    "Card2.desc":"Organizing training workshops, professional development programs, and consultations to prepare youth for the labor market and enhance their leadership and technical skills.",
    "Card3.title":"Scientific Research and Knowledge Contribution",
    "Card3.desc":"Funding and encouraging applied research related to national development, and establishing partnerships with universities and research centers.",
    "Card4.title":"Strengthening National Identity and Community Participation",
    "Card4.desc":"Implementing cultural, educational, and awareness programs aimed at instilling national values ​​and activating the role of youth in public life.",
    "Card5.title": "Building a network of Palestinian competencies",
    "Card5.desc": "linking local Palestinian competencies abroad, and activating bridges of communication between academics, researchers, and relevant institutions.",

    "footer.rights": "All rights reserved.",
    "footer.programs": "Programs",
    "footer.about": "About",
    "footer.contact": "Contact",

    "donate.hero.title": "Support Palestinian Students",
    "donate.hero.subtitle": "Your donation helps provide scholarships, educational support, and opportunities for Palestinian students worldwide.",
    "donate.form.title": "Make a Donation",
    "donate.form.amount": "Select Amount",
    "donate.form.custom": "Custom Amount",
    "donate.form.payment": "Payment Method",
    "donate.form.card": "Credit/Debit Card",
    "donate.form.bank": "Bank Transfer",
    "donate.form.button": "Donate Now",
    "donate.trust.secure": "Secure Payment",
    "donate.trust.tax": "Tax Deductible",
    "donate.impact.title": "Your Impact",
    "donate.impact.students": "Students Supported",
    "donate.impact.scholarships": "Scholarships Awarded",
    "donate.impact.countries": "Countries Reached",
    "donate.faq.title": "Frequently Asked Questions",
    "donate.faq.use": "How will my donation be used?",
    "donate.faq.use.answer": "Your donation directly supports Palestinian students through scholarships, educational programs, and academic support. We ensure transparency in fund allocation and provide regular updates on the impact of your contribution.",
    "donate.faq.tax": "Is my donation tax-deductible?",
    "donate.faq.tax.answer": "Yes, all donations to IFPPS are tax-deductible. We provide donation receipts for all contributions, which can be used for tax purposes in applicable jurisdictions.",
    "donate.faq.recurring": "Can I make a recurring donation?",
    "donate.faq.recurring.answer": "Yes, we offer monthly, quarterly, and annual recurring donation options. You can set up and manage your recurring donations through our secure payment system.",
    "donate.faq.track": "How can I track the impact of my donation?",
    "donate.faq.track.answer": "We provide regular updates through our newsletter and annual impact reports. You can also follow our success stories and student testimonials on our website and social media channels.",
    "donate.form.type": "Select Donation Type",
    "donate.form.general": "General Donation",
    "donate.form.specific": "Specific Program",
    "donate.form.select_program": "Select Program",
    "donate.form.choose_program": "Choose a program",
    "donate.form.distribution": "Financial Distribution",
    "donate.form.distribution_desc": "Your donation will be distributed as follows:",
    "donate.programs.scholarships": "Scholarships Program",
    "donate.programs.research": "Research & Development",
    "donate.programs.capacity": "Capacity Building",
    "donate.programs.pulse": "Pulse of Life Scholarship",
    "donate.programs.pulse.desc": "Full scholarships in medicine and health sciences for Palestinian students. Supporting 1,000 students over 5 years.",
    "donate.programs.talented": "Palestinian Talented Student",
    "donate.programs.talented.desc": "Supporting outstanding Palestinian students across various academic fields. 1,000 scholarships for exceptional leaders.",
    "donate.programs.sustainability": "Sustainability",
    "donate.programs.sustainability.desc": "200 scholarships in energy and agricultural engineering for Palestine's green future.",
    "donate.programs.justice": "Justice for Palestine",
    "donate.programs.justice.desc": "200 scholarships in political science and international relations for global advocacy.",
    "donate.programs.ibn-khaldun": "Ibn Khaldun",
    "donate.programs.ibn-khaldun.desc": "200 scholarships in sociology and psychology for understanding Palestinian society.",
    "donate.programs.duration": "Program Duration",
    "donate.programs.focus": "Field of Focus",

    // Ibn Khaldun Scholarship translations
    "ibn-khaldun.title": "Ibn Khaldun",
    "ibn-khaldun.subtitle": "Social Sciences Scholarship Program",
    "ibn-khaldun.tagline": "📚 Understanding Palestinian Society through Social Sciences 🧠",
    "ibn-khaldun.scholarships": "Scholarships",
    "ibn-khaldun.fields": "Key Fields",
    "ibn-khaldun.years": "Years",
    "ibn-khaldun.about.title": "About the Academic Program",
    "ibn-khaldun.about.desc": "\"Ibn Khaldun\" is a specialized graduate scholarship program designed to provide 200 full scholarships in sociology and psychology to Palestinian students. The program aims to develop competencies that can understand and analyze the social and psychological realities of Palestinians to formulate solutions and public policies.",
    "ibn-khaldun.apply": "Apply for Ibn Khaldun Scholarship",
    "ibn-khaldun.download.en": "Download Program (EN)",
    "ibn-khaldun.download.ar": "تحميل البرنامج (AR)",
    "ibn-khaldun.mission.title": "Our Mission",
    "ibn-khaldun.mission.desc": "Supporting and developing competencies that can understand and analyze the social and psychological realities of Palestinians to formulate solutions and public policies that uplift Palestinian society.",
    "ibn-khaldun.fields.title": "Fields of Study",
    "ibn-khaldun.fields.sociology.title": "Sociology",
    "ibn-khaldun.fields.sociology.desc": "Comprehensive study of social structures, institutions, and dynamics within Palestinian society to understand community relationships and cultural patterns.",
    "ibn-khaldun.fields.sociology.points": ["Social Theory & Research", "Community Development", "Cultural Studies"],
    "ibn-khaldun.fields.psychology.title": "Psychology",
    "ibn-khaldun.fields.psychology.desc": "Advanced study of individual and collective psychological processes, trauma recovery, and mental health interventions tailored to Palestinian experiences.",
    "ibn-khaldun.fields.psychology.points": ["Clinical Psychology", "Trauma & Resilience", "Community Psychology"],
    "ibn-khaldun.requirements.title": "Requirements",
    "ibn-khaldun.requirements.nationality": "Palestinian Nationality",
    "ibn-khaldun.requirements.degree": "Bachelor's Degree in social sciences or related field",
    "ibn-khaldun.requirements.gpa": "GPA 3.0+",
    "ibn-khaldun.requirements.research": "Research Interest in Palestinian social research",
    "ibn-khaldun.contact.title": "Contact Us",
    "ibn-khaldun.contact.desc": "For more information, reach out to us:",
    "ibn-khaldun.apply.now": "Apply Now",

    // Sustainability Scholarship translations
    "sustainability.title": "Sustainability Scholarship Program",
    "sustainability.subtitle": "Towards Global Sovereignty and a Society Driving Its Own Development",
    "sustainability.scholarships": "Scholarships",
    "sustainability.years": "Years",
    "sustainability.majors": "Majors",
    "sustainability.about.title": "About the Program",
    "sustainability.about.desc": "The Sustainability Scholarship Program for Graduate Studies is a national initiative by the Isnad Foundation to support Palestinian students. It aims to qualify Palestinian talents in vital fields including sustainable energy, agriculture, and natural resources, to achieve national sovereignty in energy and food, and promote sustainable development in Palestine.",
    "sustainability.why.title": "Why the Sustainability Scholarship?",
    "sustainability.why.energy.title": "Heavy Reliance on Imported Energy",
    "sustainability.why.energy.desc": "Palestine relies on imported energy for 87.4% of its needs, making it vulnerable to crises and affecting economic and social development.",
    "sustainability.why.renewable.title": "Low Contribution of Renewable Energy",
    "sustainability.why.renewable.desc": "Despite Palestine's significant natural potential for renewable energy, its contribution to local production does not exceed 4.7%.",
    "sustainability.why.agriculture.title": "Agricultural Sector Challenges",
    "sustainability.why.agriculture.desc": "The Palestinian agricultural sector faces major challenges related to water scarcity, declining cultivated areas, and weak use of modern technologies in plant, animal, and food production.",
    "sustainability.why.occupation.title": "Impact of Occupation on Natural Resources",
    "sustainability.why.occupation.desc": "The occupation depletes Palestinian natural resources and limits the ability of Palestinians to invest in them.",
    "sustainability.why.programs.title": "Lack of Specialized Academic Programs",
    "sustainability.why.programs.desc": "There are few specialized academic programs in the fields of energy, agriculture, and natural resources.",
    "sustainability.why.research.title": "Lack of Applied Scientific Research",
    "sustainability.why.research.desc": "There is a lack of applied research that contributes to developing practical solutions to local problems.",
    "sustainability.objectives.title": "Our Objectives",
    "sustainability.objectives.subtitle": "Empowering a new generation to lead Palestine's sustainable future. Here's what we're striving for:",
    "sustainability.objectives.scholarships.title": "200 Full Scholarships",
    "sustainability.objectives.scholarships": "Award 200 full scholarships to outstanding Palestinian students in energy, agriculture, and natural resources—fueling the next wave of changemakers.",
    "sustainability.objectives.research.title": "Applied Research",
    "sustainability.objectives.research": "Ignite applied scientific research that delivers real solutions for a greener, more resilient Palestine.",
    "sustainability.objectives.knowledge.title": "Knowledge & Innovation",
    "sustainability.objectives.knowledge": "Boost Palestinian knowledge and innovation, connecting research to national priorities and real-world impact.",
    "sustainability.objectives.leaders.title": "Future Leaders",
    "sustainability.objectives.leaders": "Inspire and graduate leaders ready to drive sustainable development and positive change across Palestine.",
    "sustainability.financial.title": "Financial Support",
    "sustainability.financial.tuition.title": "Academic Seats",
    "sustainability.financial.tuition.desc": "The scholarship covers annual tuition fees.",
    "sustainability.financial.tuition.amount": "$3,000",
    "sustainability.financial.tuition.period": "per academic year",
    "sustainability.financial.living.title": "Monthly Scholarship",
    "sustainability.financial.living.desc": "Students receive a monthly living stipend.",
    "sustainability.financial.living.amount": "$200",
    "sustainability.financial.living.period": "per month ($2,400/year)",
    "sustainability.financial.housing.title": "Housing Support",
    "sustainability.financial.housing.desc": "If needed, the scholarship provides annual housing support.",
    "sustainability.financial.housing.amount": "$2,400",
    "sustainability.financial.housing.period": "per year",
    "sustainability.contact.title": "Contact Us",
    "sustainability.contact.desc": "For more information, please contact us:",
    "sustainability.apply": "Apply Now",
    "sustainability.download.en": "Download Program (EN)",
    "sustainability.download.ar": "Download Program (AR)",

    // Palestinian Talented Scholarship translations
    "talented.title": "Palestinian Talented",
    "talented.subtitle": "Palestinian Talented Scholarship Program",
    "talented.tagline": "🌟 Supporting Palestinian Talent: Our Collective Responsibility ⭐",
    "talented.scholarships": "Scholarships",
    "talented.areas": "Support Areas",
    "talented.pillars": "Financial Pillars",
    "talented.about.title": "About the Palestinian Talented Scholarship Program",
    "talented.about.desc": "The \"Palestinian Talented Student Scholarship Program\" is a national initiative launched by the Isnad Foundation, offering 1,000 scholarships to outstanding students within Palestine across various academic fields. The program is designed to develop exceptional leaders across different academic fields and enable youth to achieve their full potential and serve society.",
    "talented.apply": "Apply for Talented Scholarship",
    "talented.download.en": "Download Program (EN)",
    "talented.download.ar": "تحميل البرنامج (AR)",
    "talented.why.title": "Why Support Palestinian Talent?",
    "talented.why.programs.title": "Lack of Specialized Programs",
    "talented.why.programs.desc": "There are no comprehensive national programs that support outstanding students and help them realize their potential in academic excellence and innovative projects.",
    "talented.why.environment.title": "Deprivation of an Appropriate Educational Environment",
    "talented.why.environment.desc": "Due to the lack of educational infrastructure in Palestine, many students are unable to access the resources and tools they need for development and academic success.",
    "talented.why.brain.title": "Brain Drain and Early Talent Loss",
    "talented.why.brain.desc": "The absence of early support mechanisms for exceptional students leads to the loss of many talented individuals who could have contributed to their communities.",
    "talented.why.development.title": "Lack of Talent Development Programs",
    "talented.why.development.desc": "Gifted Palestinian students often lack access to specialized programs that can nurture their talents and help them develop their skills and contribute to society.",
    "talented.why.occupation.title": "Occupation Practices Negatively Affect Well-being and Educational Opportunities",
    "talented.why.occupation.desc": "The ongoing occupation has a negative impact on the psychological and educational well-being of students. The constant stress and uncertainty make it difficult to focus on educational goals.",
    "talented.why.economic.title": "Challenging Economic Conditions Limit Access to Higher Education",
    "talented.why.economic.desc": "Financial constraints and challenging economic conditions prevent many Palestinian students from pursuing higher education and achieving their dreams.",
    "talented.why.achievement.title": "Outstanding Achievement is Difficult to Achieve Without Marginalized Support",
    "talented.why.achievement.desc": "To achieve outstanding results, students need comprehensive support that includes financial assistance, mentorship, and access to advanced educational resources.",
    "talented.why.infrastructure.title": "Limited Access to Quality Educational Infrastructure",
    "talented.why.infrastructure.desc": "Many Palestinian students lack access to modern educational facilities, advanced laboratories, and cutting-edge technology that are essential for academic excellence and innovation.",
    "talented.goals.title": "Our Goals",
    "talented.goals.scholarships": "Award 1,000 full scholarships to outstanding Palestinian students",
    "talented.goals.leaders": "Develop exceptional leaders across different academic fields",
    "talented.goals.potential": "Enable youth to achieve their full potential and serve society",
    "talented.financial.title": "Excellence Scholarship Financial Support",
    "talented.financial.academic.title": "Academic Tuition",
    "talented.financial.academic.desc": "Full coverage of the Palestinian Talented Scholarship Program costs",
    "talented.financial.academic.amount": "$2,500",
    "talented.financial.academic.period": "per academic year",
    "talented.financial.stipend.title": "Monthly Scholarship",
    "talented.financial.stipend.desc": "Monthly living expenses support",
    "talented.financial.stipend.amount": "$200",
    "talented.financial.stipend.period": "monthly ($2,400/year)",
    "talented.financial.technology.title": "Electronic Device Support",
    "talented.financial.technology.desc": "One-time device purchase support",
    "talented.financial.technology.amount": "$300",
    "talented.financial.technology.period": "one-time grant",
    "talented.requirements.title": "Requirements",
    "talented.requirements.nationality": "Palestinian Nationality",
    "talented.requirements.average": "High School Average ≥ 90%",
    "talented.requirements.gpa": "GPA 3.00+",
    "talented.requirements.english": "English Proficiency Preferred",
    "talented.fields.title": "Fields of Study",
    "talented.fields.business": "Business Administration",
    "talented.fields.engineering": "Engineering",
    "talented.fields.education": "Education",
    "talented.fields.social": "Social Sciences",
    "talented.fields.computer": "Computer Science",
    "talented.fields.international": "International Relations",
    "talented.fields.economics": "Economics",
    "talented.fields.law": "Law",
    "talented.fields.psychology": "Psychology",
    "talented.fields.media": "Media & Communications",
    "talented.contact.title": "Contact Us",
    "talented.contact.desc": "For more information, reach out to us:",
    "talented.apply.now": "Apply Now",

    // Home page News & Announcements section
    "news.badge": "Latest Updates",
    "news.title": "Latest News",
    "news.subtitle": "Stay informed with our latest news, updates, and important announcements from the foundation.",
    "news.viewAll": "View All News",

    // Home page Our Programs section
    "programs.badge": "Scholarship Programs",
    "programs.title": "Our Programs",
    "programs.subtitle": "Empowering Palestinian students through specialized scholarship programs",
    "programs.pulse.title": "Pulse of Life Scholarship",
    "programs.pulse.category": "Medical & Health Sciences",
    "programs.pulse.scholarships": "1,000 Scholarships Over 5 Years",
    "programs.pulse.description": "A bold national initiative providing full scholarships in medicine and health sciences, focusing on rare and critical specializations to strengthen healthcare in Palestine.",
    "programs.pulse.focus": "Program Focus",
    "programs.pulse.features": "Key Features",
    "programs.pulse.medical": "Medical Education",
    "programs.pulse.innovation": "Healthcare Innovation",
    "programs.pulse.full": "Full Scholarships",
    "programs.pulse.years": "5-Year Program",
    "programs.talented.title": "Palestinian Talented scholarship",
    "programs.talented.category": "Excellence Scholarship",
    "programs.talented.scholarships": "1,000 Scholarships Available",
    "programs.talented.description": "Supporting outstanding Palestinian students across various academic fields, developing exceptional leaders who will drive innovation and progress in their communities.",
    "programs.talented.focus": "Program Focus",
    "programs.talented.features": "Key Features",
    "programs.talented.excellence": "Academic Excellence",
    "programs.talented.leadership": "Leadership Development",
    "programs.talented.fields": "Multiple Fields",
    "programs.talented.support": "Comprehensive Support",
    "programs.explore": "Explore All Programs",

    // Home page Your Path to Success section
    "journey.badge": "Student Journey",
    "journey.title": "Your Path to Success",
    "journey.subtitle": "From application to graduation, we provide comprehensive support at every step of your academic journey.",
    "journey.application.title": "Application",
    "journey.application.description": "Submit your application through our streamlined process. We review each application carefully to identify promising candidates.",
    "journey.application.form": "Online Application Form",
    "journey.application.documents": "Document Submission",
    "journey.application.screening": "Initial Screening",
    "journey.selection.title": "Selection",
    "journey.selection.description": "Our expert committee evaluates candidates based on academic excellence, leadership potential, and commitment to community.",
    "journey.selection.review": "Academic Review",
    "journey.selection.interview": "Interview Process",
    "journey.selection.final": "Final Selection",
    "journey.support.title": "Support",
    "journey.support.description": "Receive comprehensive support throughout your academic journey, including financial aid, mentorship, and career guidance.",
    "journey.support.financial": "Financial Support",
    "journey.support.mentoring": "Academic Mentoring",
    "journey.support.career": "Career Development",
    "journey.success.title": "Success",
    "journey.success.description": "Join our network of successful graduates who are making a difference in their communities and beyond.",
    "journey.success.graduation": "Graduation Support",
    "journey.success.alumni": "Alumni Network",
    "journey.success.opportunities": "Career Opportunities",
    "journey.start": "Start Your Journey",

    // Home page Call to Action section
    "cta.title": "Join Us in Empowering Palestinian Students",
    "cta.description": "Your support can make a lasting impact on the lives of talented Palestinian students. Together, we can build a brighter future through education.",
    "cta.button": "Donate Now",

    // Home page Partners section
    "partners.badge": "Our Partners",
    "partners.title": "Working Together for Change",
    "partners.subtitle": "We collaborate with leading institutions and organizations to provide comprehensive support to Palestinian students.",

    // Home page Contact section
    "contact.badge": "Get in Touch",
    "contact.button": "Contact Our Team",

    // Stats section
    "stats.scholarships": "Scholarships Awarded",
    "stats.beneficiaries": "beneficiaries",
    "stats.countries": "Countries Reached",
    "stats.graduation": "Graduation Rate %",

    // Footer section
    "footer.description": "Empowering Palestinian students worldwide through educational opportunities, financial support, and academic resources.",
    "footer.programs.undergraduate": "Undergraduate Programs",
    "footer.programs.graduate": "Graduate Programs",
    "footer.programs.research": "Research Programs",
    "footer.about.mission": "Our Mission",
    "footer.about.team": "Team",
    "footer.about.partners": "Partners",

    // About page specific translations
    "about.page.indicator": "Who Are We",
    "about.purpose.badge": "Our Purpose",
    "about.purpose.title": "Mission & Vision",
    "about.purpose.subtitle": "Guided by our commitment to educational equity and empowerment for Palestinian students worldwide.",
    "about.mission.point1": "Provide scholarships to talented Palestinian students",
    "about.mission.point2": "Create educational opportunities through global partnerships",
    "about.mission.point3": "Support academic and professional development",
    "about.vision.point1": "A world where every Palestinian student has access to quality education",
    "about.vision.point2": "A global network of Palestinian scholars and professionals",
    "about.vision.point3": "Educational empowerment as a path to community development",
    "about.partners.badge": "Collaborations",
    "about.partners.title": "Our Partners",
    "about.partners.subtitle": "We collaborate with universities, educational institutions, and organizations worldwide to expand opportunities for Palestinian students.",
    "about.cta.title": "Join Us",
    "about.cta.subtitle": "Whether you're a student looking for support, a potential partner, or someone who wants to contribute to our cause, we'd love to hear from you.",
    "about.cta.contact": "Contact Us",
    "about.cta.support": "Support Our Work",

    // Pulse of Life page translations
    "pulse.title": "Pulse of Life",
    "pulse.subtitle": "Medical Scholarship Program",
    "pulse.tagline": "🩺 The Health of Palestine... Our Responsibility 🏥",
    "pulse.stats.scholarships": "Scholarships",
    "pulse.stats.years": "Years",
    "pulse.stats.pillars": "Support Pillars",
    "pulse.about.title": "About the Program",
    "pulse.about.description": "is a bold national initiative launched by the Isnad Foundation, aiming to provide 1,000 full scholarships in medicine and health sciences to Palestinian students inside and outside Palestine—especially in rare and critical specializations. The program is designed to run over a period of 5 years.",
    "pulse.apply": "Apply for Pulse of Life Scholarship",
    "pulse.download.en": "Download Program (EN)",
    "pulse.download.ar": "تحميل البرنامج (AR)",
    "pulse.why.title": "Why Pulse of Life?",
    "pulse.why.shortage.title": "Shortage of Medical Personnel",
    "pulse.why.shortage.description": "There is a critical lack of qualified medical and healthcare professionals, which limits service delivery and reduces the quality of care in health institutions.",
    "pulse.why.specialized.title": "Lack of Specialized Fields",
    "pulse.why.specialized.description": "The local healthcare system suffers from a shortage of specialists in key medical fields, further straining the Ministry of Health and limiting advanced care options.",
    "pulse.why.capacity.title": "Shortage in Hospital Capacity",
    "pulse.why.capacity.description": "A lack of hospital beds and essential resources means many patients cannot receive timely care, leading to higher mortality rates and overwhelming existing facilities.",
    "pulse.why.infrastructure.title": "Poor Healthcare Infrastructure",
    "pulse.why.infrastructure.description": "Many medical devices are out of service, and essential resources to run healthcare facilities efficiently are missing, making it difficult to provide adequate care.",
    "pulse.why.occupation.title": "Impact of the Israeli Occupation",
    "pulse.why.occupation.description": "Since 2023, ongoing Israeli attacks have destroyed numerous health facilities, severely limiting the ability to deliver services and reducing the overall capacity of the healthcare system.",
    "pulse.goals.title": "Our Goals",
    "pulse.goals.train": "Train 1,000 students in medicine and health sciences through full scholarships.",
    "pulse.goals.support": "Support local healthcare by integrating graduates into the system.",
    "pulse.goals.reach": "Reach underserved areas through mobile clinics and awareness efforts.",
    "pulse.financial.title": "Pulse of Life Scholarship Financial Support",
    "pulse.financial.education.title": "Academic Seats",
    "pulse.financial.education.description": "Full coverage of medical education costs",
    "pulse.financial.education.amount": "$5,600",
    "pulse.financial.education.period": "per academic year",
    "pulse.financial.stipend.title": "Monthly Stipend",
    "pulse.financial.stipend.description": "Monthly living expenses support",
    "pulse.financial.stipend.amount": "$200",
    "pulse.financial.stipend.period": "monthly ($2,400/year)",
    "pulse.financial.technology.title": "Electronic Equipment Purchase Grant",
    "pulse.financial.technology.description": "One-time device purchase support",
    "pulse.financial.technology.amount": "$300",
    "pulse.financial.technology.period": "one-time grant",
    "pulse.requirements.title": "Requirements",
    "pulse.requirements.nationality": "Palestinian Nationality",
    "pulse.requirements.average": "High School Average ≥ 90%",
    "pulse.requirements.gpa": "GPA 3.00+",
    "pulse.requirements.english": "English Proficiency Preferred",
    "pulse.fields.title": "Fields of Study",
    "pulse.fields.medicine": "Human Medicine",
    "pulse.fields.dentistry": "Dentistry",
    "pulse.fields.pharmacy": "Pharmacy",
    "pulse.fields.allied": "Allied Health Professions",
    "pulse.fields.nursing": "Nursing",
    "pulse.apply.now": "Apply Now",
    "pulse.news.title": "Latest Program Updates",
    "pulse.news.subtitle": "Isnad Foundation Begins Disbursement of Pulse of Life Scholarships in Partnership with the Turkish National Youth Foundation (MGV)",
    "pulse.news.disbursement.title": "Disbursements Begin",
    "pulse.news.disbursement.description": "The first phase of Pulse of Life scholarship disbursements has officially begun in Turkey, supporting Palestinian medical students.",
    "pulse.news.watch.videos": "Watch Latest Videos",
    "pulse.news.read.more": "Read Full Article",
    "pulse.contact.title": "Contact Us",
    "pulse.contact.description": "For more information, reach out to us:",

    // Justice for Palestine translations
    "justice.title": "Justice for Palestine",
    "justice.subtitle": "Advocacy Scholarship Program",
    "justice.tagline": "⚖️ Preparing Palestinian Leaders for Global Advocacy 🇵🇸",
    "justice.scholarships": "Scholarships",
    "justice.fields": "Key Fields",
    "justice.years": "Years",
    "justice.about.title": "About the Justice Program",
    "justice.about.desc": "Justice for Palestine is a specialized graduate scholarship program designed to provide 200 full scholarships in political science and international relations to Palestinian students. The program aims to prepare qualified Palestinian professionals for political, diplomatic, and international advocacy roles.",
    "justice.apply": "Apply for Justice Scholarship",
    "justice.download.en": "Download Program (EN)",
    "justice.download.ar": "تحميل البرنامج (AR)",
    "justice.mission.title": "Our Mission",
    "justice.mission.desc": "Preparing qualified Palestinian professionals for political, diplomatic, international, and crisis management roles to enable them to advocate for Palestine globally and advance the Palestinian cause on the international stage.",
    "justice.fields.title": "Fields of Study",
    "justice.fields.political.title": "Political Science",
    "justice.fields.political.desc": "Advanced studies in political theory, governance, public policy, and political analysis to develop expertise in understanding political systems.",
    "justice.fields.political.points": ["Political Theory", "Public Policy Analysis", "Comparative Politics"],
    "justice.fields.international.title": "International Relations",
    "justice.fields.international.desc": "Comprehensive training in diplomacy, international law, conflict resolution, and global governance for international advocacy roles.",
    "justice.fields.international.points": ["Diplomatic Studies", "International Law", "Conflict Resolution"],
    "justice.requirements.title": "Requirements",
    "justice.requirements.nationality": "Palestinian Nationality",
    "justice.requirements.degree": "Bachelor's Degree in political science, law, or related field",
    "justice.requirements.gpa": "GPA 3.0+",
    "justice.requirements.interest": "Interest in political and international advocacy",
    "justice.contact.title": "Contact Us",
    "justice.contact.description": "For more information about the Justice for Palestine scholarship program, reach out to us:",
    "justice.contact.desc": "For more information, reach out to us:",

    // News page translations
    "news.hero.alt": "Latest News Hero Image",
    "news.latest": "Latest News",
    "news.featured.badge": "Featured",
    "news.featured.title": "Featured Stories",
    "news.featured.subtitle": "Highlighting our most important updates and announcements.",
    "news.archive.badge": "Archive",
    "news.archive.title": "News Archive",
    "news.archive.subtitle": "Browse our complete collection of news, updates, and announcements.",
    "news.search.placeholder": "Search news...",
    "news.filter.placeholder": "Filter by category",
    "news.tabs.all": "All News",
    "news.tabs.featured": "Featured",
    "news.tabs.recent": "Recent",
    "news.readMore": "Read More",
    "news.noResults": "No news articles found matching your criteria.",
    "news.backToNews": "Back to News",
    "news.moreNews": "More News",
    "news.moreNewsDesc": "Explore our other news articles and updates",
    "news.viewprograms": "View Our Programs",
    "news.relatedArticles": "Related Articles",
    "news.categories": "Categories",
    "news.explorePrograms": "Explore Our Programs",
    "news.exploreProgramsDesc": "Discover our scholarship programs and educational initiatives",
    "news.viewPrograms": "View All Programs",
    "news.share": "Share this article",
    "news.linkCopied": "Link copied to clipboard",


  "news.latest.supportTour.title": "Isnad Conducts Support Tours in Six Countries and Provides Educational Grants to Gaza Students",
  "news.latest.supportTour.excerpt": "Since the beginning of the genocide war in the Gaza Strip, the Isnad Foundation for Palestinian Student Support has implemented a series of meetings and events in several countries including Turkey, Egypt, Mauritania, Kyrgyzstan, Malaysia, and the Gaza Strip, as part of its urgent response to the needs of Palestinian students affected by the ongoing war on the Gaza Strip since October 2023.",
  "news.latest.supportTour.category": "Education & Humanitarian Support",
  "news.latest.supportTour.date": "June 06, 2024",

  "news.latest.pulseOfLifeStart.title":  "Continuation of First Phase Interviews for Pulse of Life Scholarship to Select 100 Students from Gaza",
  "news.latest.pulseOfLifeStart.excerpt": "تواصلت اليوم الإثنين مقابلات المرحلة الأولى من برنامج منحة نبض الحياة، الذي تنفذه مؤسسة إسنَاد لدعم الطالب الفلسطيني بالشراكة مع مؤسسة الخدمات أوروبا (Alkhidmat Europe)، والتي تستهدف طلبة الطب الفلسطينيين خاصة في قطاع غزة.",
  "news.latest.pulseOfLifeStart.category": "Scholarships",
  "news.latest.pulseOfLifeStart.date": "May 5, 2025",

  "news.latest.pulseOfLifeEnd.title": "Completion of First Phase of Pulse of Life Scholarship Interviews",
  "news.latest.pulseOfLifeEnd.excerpt": "The Isnad Foundation for Palestinian Student Support concluded, on Saturday, May 25, 2025, the first phase of the 'Pulse of Life' scholarship interviews, which extended over three weeks starting from May 5, with the participation of dozens of outstanding Palestinian students in the field of human medicine.",
  "news.latest.pulseOfLifeEnd.category": "Scholarships",
  "news.latest.pulseOfLifeEnd.date": "May 25, 2025",
  
    "stats.partners": "Partners",
    "stats.pillars": "Pillars of Support",

    // Contact page translations
    "contact.getInTouch": "Get in Touch",
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions about our programs or application process? Our team is here to help you navigate your educational journey.",
    "contact.phone": "+90 (539) 4300 726",
    "contact.email": "info@isnadf.org",
    "contact.info.title": "Contact Information",
    "contact.info.subtitle": "If you have questions about our programs, the application process, or would like to learn more about our organization, we are here to help.",
    "contact.location.title": "Our Location",
    "contact.location.address": "Kayabaşı Mah. Adnan Menderes Blv. A4 Blok No:7A Kapı No:11 Başakşehir/İstanbul",
    "contact.email.title": "Email Us",
    "contact.email.secondary": "Palestinian.pssf@gmail.com",
    "contact.phone.title": "Call Us",
    "contact.phone.hours": "Monday-Friday, 9:00 AM - 5:00 PM (GMT+3)",
    "contact.follow.title": "Follow Us",
    "contact.form.title": "Send Us a Message",
    "contact.form.subtitle": "Fill out the form below and we'll get back to you as soon as possible.",
    "contact.form.name": "Your Name",
    "contact.form.name.placeholder": "Enter your name",
    "contact.form.email": "Email Address",
    "contact.form.email.placeholder": "Enter your email",
    "contact.form.subject": "Subject",
    "contact.form.subject.placeholder": "Enter subject",
    "contact.form.message": "Message",
    "contact.form.message.placeholder": "Enter your message",
    "contact.form.submit": "Send Message",
    "contact.map.title": "our location",
    "contact.office.title": "Take a Look Inside",
    "contact.office.subtitle": "Get a glimpse of our office space where we work to support Palestinian students in their educational journey.",
    "contact.office.entrance": "Office entrance",
    "contact.office.workspace": "Office workspace",
    "contact.office.meeting": "Office meeting room",

    "contact.info.subtitle3": "Reach out to us using any of the methods below.",

    // Success Stories translations
    "success_stories.page_indicator": "Success Stories",
    "success_stories.title": "Success Stories",
    "success_stories.subtitle": "Meet the remarkable students who have transformed their lives through our support programs.",
    "success_stories.inspiring_journeys": "Inspiring Journeys",
    "success_stories.featured_stories": "Featured Stories",
    "success_stories.featured_description": "Inspiring journeys of determination, resilience, and academic excellence.",
    "success_stories.mandela_quote": "Education is the most powerful weapon which you can use to change the world.",
    "success_stories.mandela_author": "Nelson Mandela",
    "success_stories.browse_stories": "Browse Stories",
    "success_stories.all_stories": "All Success Stories",
    "success_stories.browse_description": "Browse through the inspiring journeys of our scholarship recipients.",
    "success_stories.search_placeholder": "Search stories...",
    "success_stories.degree_level": "Degree Level",
    "success_stories.graduation_year": "Graduation Year",
    "success_stories.tabs.all": "All Stories",
    "success_stories.tabs.featured": "Featured",
    "success_stories.read_full_story": "Read Full Story",
    "success_stories.no_stories_found": "No success stories found matching your criteria.",
    "success_stories.your_journey_matters": "Your Journey Matters",
    "success_stories.share_story_title": "Share Your Success Story",
    "success_stories.share_story_description": "Are you a scholarship recipient with a story to tell? We'd love to feature your journey and inspire others.",
    "success_stories.submit_story": "Submit Your Story",
    "success_stories.categories.bachelors": "Bachelor's",
    "success_stories.categories.masters": "Master's",
    "success_stories.categories.phd": "PhD",
    "success_stories.back_to_stories": "Back to Stories",

    "testimonials.hero.title": "Isnad's Footprint in Our Students' Journey",
    "testimonials.hero.subtitle": "Hear directly from students about their experiences and the impact of our programs.",
    "testimonials.student_voices": "Beneficiary students",
    "testimonials.student_testimonials": "Student Testimonials",
    "testimonials.student_description": "See what Palestinian students have to say about our organization.",
    "testimonials.public_figures": "Public Figures",
    "testimonials.public_figure_testimonials": "Public Figure Testimonials",
    "testimonials.public_figure_description": "We are proud of the testimonies of distinguished figures about our institution.\nThey mean a lot to us and give us motivation\nto continue striving to serve Palestinian students around the world.",
    "ibn-khaldun.reents.research": "Research Interest in Palestinian social issues",
    "ibn-khaldun.problems.title": "Problem Indicators",
    "ibn-khaldun.problems.experts": "SHORTAGE OF EXPERTS IN SOCIAL SCIENCES",
    "ibn-khaldun.problems.experts.desc": "Local reports point to a significant gap in the number of qualified academics and researchers in sociology relative to the scale of socio-economic challenges that require specialized research-based interventions.",
    "ibn-khaldun.problems.fragmentation": "RISING SOCIAL FRAGMENTATION AND PSYCHOLOGICAL PRESSURE",
    "ibn-khaldun.problems.fragmentation.desc": "Emerging behavioral patterns indicate that a significant portion of Palestinian youth are experiencing forms of family or social disintegration due to war, displacement, and unemployment. This calls for analytical research efforts to understand and address shifting social dynamics.",
    "ibn-khaldun.problems.research": "SPECIALIZED RESEARCH INSTITUTIONS CONTROLLED BY THE OCCUPATION",
    "ibn-khaldun.problems.research.desc": "The psychological, social, and historical study of Palestinian society has been utilized for purposes of control and domination, with psychological and social knowledge being employed in soft colonial strategies, such as psychological and media warfare.",
    "ibn-khaldun.problems.local": "WEAK LOCAL RESEARCH IN SOCIOLOGY",
    "ibn-khaldun.problems.local.desc": "Less than 3% of Palestine's annual research output focuses on the social sciences. A major disconnect exists between real societal issues and academic production capable of interpreting and addressing them.",
    "ibn-khaldun.problems.programs": "LIMITED GRADUATE PROGRAMS IN RELEVANT FIELDS",
    "ibn-khaldun.problems.programs.desc": "Palestinian universities offer a very limited number of master's and doctoral programs in sociology or related fields. These programs often lack practical training and effective integration of theory with real-world social contexts.",
    "ibn-khaldun.problems.policy": "WEAK INTEGRATION OF RESEARCH AND PUBLIC POLICY",
    "ibn-khaldun.problems.policy.desc": "Outputs of social research are rarely used in decision-making. There is a clear lack of coordination between universities and state institutions, which significantly limits the ability of researchers to influence the development of social and developmental policies.",
    "ibn-khaldun.financial.title": "Financial Support Structure",
    "ibn-khaldun.financial.tuition.title": "Tuition Support",
    "ibn-khaldun.financial.stipend.title": "Monthly Stipend",
    "ibn-khaldun.financial.total.title": "Total Financial Support",
    "ibn-khaldun.financial.tuition.desc": "Covers the cost of academic tuition across various disciplines, with an average annual support of $3,000 per student.",
    "ibn-khaldun.financial.stipend.desc": "Provides an average monthly allowance of $200 to support students' basic living needs, such as housing and transportation, totaling $2,400 annually.",
    "ibn-khaldun.financial.total.annual": "Total Annual Cost per Student",
    "ibn-khaldun.financial.total.fiveYear": "Total 5-Year Cost per Student",
    "ibn-khaldun.financial.perYear": "per year",
    "ibn-khaldun.financial.note": "Note: The actual costs may vary depending on the university and program of study.",

    // Programs page translations
    "programs.hero.title": "Scholarship Programs",
    "programs.hero.subtitle": "Empowering Palestinian Students Through Education Excellence",
    "programs.hero.flag.alt": "Palestinian Flag",
    "programs.section.title": "Our Programs",
    "programs.section.subtitle": "Choose your path to educational excellence",
    "programs.undergraduate.title": "Undergraduate Programs",
    "programs.postgraduate.title": "Postgraduate Programs",
    "programs.postgraduate.subtitle": "Advanced degrees for specialized expertise",
    "programs.sustainability.title": "Sustainability",
    "programs.sustainability.description": "200 scholarships in energy and agricultural engineering for Palestine's green future.",
    "programs.justice.title": "Justice for Palestine",
    "programs.justice.description": "200 scholarships in political science and international relations for global advocacy.",
    "programs.ibn-khaldun.title": "Ibn Khaldun",
    "programs.ibn-khaldun.description": "200 scholarships in sociology and psychology for understanding Palestinian society.",
    "programs.learn-more": "Learn More",

"testimonials.hero.subtitle_influencers": "Hear directly from students about their experiences and the impact of our programs.",

  },
  ar: {
      "news.latest.pulseOfLifeDisbursement.title": "بدء صرف منح المرحلة الأولى من برنامج نبض الحياة في تركيا",
      "news.latest.pulseOfLifeDisbursement.excerpt": "أعلنت مؤسسة إسناد لدعم الطالب الفلسطيني عن بدء صرف المنح الدراسية للطلبة المستفيدين ضمن المرحلة الأولى من برنامج نبض الحياة، وذلك اعتبارًا من 1 مايو 2025",


    "contact.info.subtitlquireme3": "تواصل معنا باستخدام أي من الطرق أدناه :",
    // Navigation translations
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.programs": "برامجنا",
    "nav.programs.undergraduate": "منح البكالوريوس",
    "nav.programs.graduate": "منح الدراسات العليا",
    "nav.donate": "تبرع",
    "nav.contact": "اتصل بنا",
    "nav.news": "آخر الأخبار",
    "nav.activities": "الأنشطة السابقة",
    "nav.testimonials": "الشهادات",
    "nav.media": "الإعلام",
    "nav.media.success": "قصص النجاح",
    "nav.media.activities": "الأنشطة السابقة",
    "nav.media.testimonials": "قالوا عنا ",
    "nav.educational.environment": "البيئة التعليمية",

    // Remove duplicate hero translations
    "about.widgt": "القيم",
    "about.title":"قيمنا",
    "about.subtitle":"IFPPS",
    "about.identity": "الانتماء الوطني",
    "about.identity.desc": "نعمل انطلاقًا من التزامنا الراسخ بالقضية الفلسطينية، ونسعى جاهدين لترسيخ الهوية الوطنية في كل ما نقوم به",
    "about.identity2":"التميز الأكاديمي",
    "about.identity2.desc":"ندعم المواهب العلمية والأكاديمية، ونشجع على السعي الدائم نحو التميز والمعرفة",
    "about.identity3":"العدالة وتكافؤ الفرص",
    "about.identity3.desc":"نؤمن بضرورة توفير الفرص للمجتمع على أساس الكفاءة والجدارة، دون تمييز",
    "about.identity4":"الشفافية والنزاهة",
    "about.identity4.desc":"نؤدي عملنا بروح من الوضوح والمساءلة، محافظين على الثقة المتبادلة مع شركائنا",
    "about.identity5":"الاستدامة",
    "about.identity5.desc":"نخطط ونعمل بروح استشرافية تضمن أثرًا إيجابيًا طويل الأمد على المجتمع الفلسطيني",
    "about.identity6":"تمكين الشباب",
    "about.identity6.desc":"نؤمن بأهمية دعم وتمكين المواهب الأكاديمية الفلسطينية الشابة، فهم المحرك الأساسي لبناء المستقبل وتحقيق التنمية الوطنية المستدامة",
    "about.identity7":"المبادرة",
    "about.identity7.desc":"نسعى باستمرار لتحديد احتياجات الطلاب، وتقديم مشاريع تلبي هذه الاحتياجات، وتشجيعهم على إطلاق مبادرات مجتمعية",
    "about.cta":"من نحن",

    "hero.title": "تمكين الطلاب الفلسطينيين حول العالم",
    "hero.subtitle":
      "تقديم المنح الدراسية والمساعدة في القبول الجامعي والدعم الأكاديمي لمساعدة الطلاب الفلسطينيين على تحقيق أحلامهم التعليمية.",
    "hero.cta.apply": "التقدم للمنحة",
    "hero.cta.explore": "استكشاف البرامج",
    "about.hero.title": "من نحن؟",
    "about.hero.description": "مؤسسة إسنَاد لدعم الطالب الفلسطيني هي كيان تنموي مستقل وغير ربحي، يهدف إلى دعم مسيرة التعليم العالي في فلسطين عبر الاستثمار في الطاقات الشبابية الأكاديمية. تركز المؤسسة على تقديم برامج ومبادرات تساهم في سد الفجوة بين مخرجات التعليم واحتياجات المجتمع، من خلال توفير منح دراسية، وتيسير الوصول إلى التخصصات ذات الأولوية الوطنية. كما تعمل على خلق شبكة معرفية تجمع بين الكفاءات الفلسطينية داخل الوطن وفي الشتات، ضمن رؤية تنموية شاملة",
    "about.mission.tag": "رسالتنا",
    "about.mission.title": "التمكين من خلال التعليم",
    "about.mission.text":"الارتقاء بالكفاءات الأكاديمية الفلسطينية الشابة في شتى التخصصات التي يحتاجها المجتمع الفلسطيني، وتمكينها من أداء دور محوري وفعّال في بناء مستقبل مستدام، مزدهر، وقوي للدولة الفلسطينية.",
    "about.vision.tag": "رؤيتنا",
    "about.vision.title": "بناء قادة المستقبل",
    "about.vision.text": "تؤمن مؤسسة إسنَاد لدعم الطالب الفلسطيني بأهمية تعزيز دور الشباب في النشاط المجتمعي، عبر برامج تعليمية وتوعوية تهدف إلى ترسيخ مفاهيم التفاعل، والانسجام الاجتماعي، والانتماء الوطني.",
    "about.foundation.tag": "هوية المؤسسة",
    "about.foundation.title": "قصتنا",
    "about.foundation.text1": "تأسست مؤسسة إسنَاد لدعم الطالب الفلسطيني في عام 2015 في إسطنبول، تركيا، على يد مجموعة من المربين والمهنيين الذين أدركوا التحديات التي يواجهها الطلاب الفلسطينيون الساعون للحصول على فرص التعليم العالي.",
    "about.foundation.text2": "ما بدأ كمبادرة صغيرة لتقديم المنح الدراسية لعدد قليل من الطلاب نما ليصبح مؤسسة دعم شاملة ساعدت مئات الطلاب الفلسطينيين في الوصول إلى تعليم عالي الجودة في جميع أنحاء العالم.",
    "about.foundation.text3": "مؤسستنا مسجلة كمنظمة تعليمية غير ربحية في تركيا، تعمل بشفافية ومسؤولية كاملة تجاه المانحين والشركاء.",
    "about.team.tag": "الهيكل الإداري",
    "about.team.title": "فريقنا",
    "about.team.viewAll": "عرض الفريق بالكامل",
    "about.team.member1.name": "د. محمود عباس",
    "about.team.member1.title": "المدير التنفيذي",
    "about.team.member1.description": "أستاذ جامعي سابق مع أكثر من 20 عام من الخبرة في الإدارة التعليمية.",
    "about.team.member2.name": "د. ليلى خالد",
    "about.team.member2.title": "المدير الأكاديمي",
    "about.team.member2.description": "متخصصة في سياسة التعليم الدولي وبرامج إرشاد الطلاب.",
    "about.team.member3.name": "عمر فاروق",
    "about.team.member3.title": "المدير المالي",
    "about.team.member3.description": "خبير في الإدارة المالية للمنظمات غير الربحية وإدارة صناديق المنح الدراسية.",

    "work.badget":"التعليم، التمكين، التواصل",
    "work.title":"مجالات عمل المؤسسة",
    "work.subtitle": "تمكين الشباب الفلسطيني من خلال التعليم والابتكار والتواصل",
    "card1.title":"المنح الدراسية والدعم الأكاديمي",
    "Card1.desc":"توفير منح دراسية للشباب الفلسطيني في تخصصات يحتاجها سوق العمل والمجتمع داخل فلسطين وخارجها.",
    "Card2.title":"بناء القدرات والتطوير المهني",
    "Card2.desc":"تنظيم ورش عمل تدريبية وبرامج تطوير مهني واستشارات لإعداد الشباب لسوق العمل وتعزيز مهاراتهم القيادية والتقنية.",
    "Card3.title":"البحث العلمي والمساهمة المعرفية",
    "Card3.desc":" تمويل وتشجيع البحوث التطبيقية المتعلقة بالتنمية الوطنية، وإقامة شراكات مع الجامعات ومراكز البحوث.",
    "Card4.title":"تعزيز الهوية الوطنية والمشاركة المجتمعية",
    "Card4.desc":"تنفيذ برامج ثقافية وتعليمية وتوعوية تهدف إلى ترسيخ القيم الوطنية وتفعيل دور الشباب في الحياة العامة.",
    "Card5.title": "بناء شبكة كفاءات فلسطينية",
    "Card5.desc": "ربط الكفاءات الفلسطينية المحلية بالخارج، وتفعيل جسور التواصل بين الأكاديميين والباحثين والمؤسسات ذات العلاقة.",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.programs": "البرامج",
    "footer.about": "عن المؤسسة",
    "footer.contact": "اتصل بنا",

    "donate.hero.title": "دعم الطلاب الفلسطينيين",
    "donate.hero.subtitle": "تبرعك يساعد في توفير المنح الدراسية والدعم التعليمي والفرص للطلاب الفلسطينيين حول العالم",
    "donate.form.title": "تبرع الآن",
    "donate.form.amount": "اختر المبلغ",
    "donate.form.custom": "مبلغ مخصص",
    "donate.form.payment": "طريقة الدفع",
    "donate.form.card": "بطاقة ائتمان/خصم",
    "donate.form.bank": "تحويل بنكي",
    "donate.form.button": "تبرع الآن",
    "donate.trust.secure": "دفع آمن",
    "donate.trust.tax": "معفى من الضرائب",
    "donate.impact.title": "تأثيرك",
    "donate.impact.students": "طالب مدعوم",
    "donate.impact.scholarships": "منحة مقدمة",
    "donate.impact.countries": "دولة مستفيدة",
    "donate.faq.title": "الأسئلة الشائعة",
    "donate.faq.use": "كيف سيتم استخدام تبرعي؟",
    "donate.faq.use.answer": "يذهب تبرعك مباشرة لدعم الطلاب الفلسطينيين من خلال المنح الدراسية والبرامج التعليمية والدعم الأكاديمي. نحن نضمن الشفافية في توزيع الأموال ونقدم تحديثات منتظمة عن تأثير مساهمتك.",
    "donate.faq.tax": "هل تبرعي معفى من الضرائب؟",
    "donate.faq.tax.answer": "نعم، جميع التبرعات لصندوق الإسناد الفلسطيني معفاة من الضرائب. نحن نقدم إيصالات التبرع لجميع المساهمات، والتي يمكن استخدامها للأغراض الضريبية في الولايات القضائية المعمول بها.",
    "donate.faq.recurring": "هل يمكنني تقديم تبرع متكرر؟",
    "donate.faq.recurring.answer": "نعم، نقدم خيارات التبرع المتكرر شهرياً وربع سنوياً وسنوياً. يمكنك إعداد وإدارة تبرعاتك المتكررة من خلال نظام الدفع الآمن لدينا.",
    "donate.faq.track": "كيف يمكنني متابعة تأثير تبرعي؟",
    "donate.faq.track.answer": "نقدم تحديثات منتظمة من خلال النشرة الإخبارية وتقارير التأثير السنوية. يمكنك أيضاً متابعة قصص النجاح وشهادات الطلاب على موقعنا الإلكتروني وقنوات التواصل الاجتماعي.",
    "donate.form.type": "اختر نوع التبرع",
    "donate.form.general": "تبرع عام",
    "donate.form.specific": "تبرع لبرنامج محدد",
    "donate.form.select_program": "اختر البرنامج",
    "donate.form.choose_program": "اختر برنامجاً",
    "donate.form.distribution": "التوزيع المالي",
    "donate.form.distribution_desc": "Your donation will be distributed as follows:",
    "donate.programs.scholarships": "برنامج المنح الدراسية",
    "donate.programs.research": "البحث والتطوير",
    "donate.programs.capacity": "بناء القدرات",
    "donate.programs.pulse": "منحة نبض الحياة",
    "donate.programs.pulse.desc": "منح دراسية كاملة في الطب والعلوم الصحية للطلاب الفلسطينيين. دعم 1,000 طالب على مدى 5 سنوات.",
    "donate.programs.talented": "الطلاب الفلسطينيون الموهوبون",
    "donate.programs.talented.desc": "دعم الطلاب الفلسطينيين المتميزين في مختلف المجالات الأكاديمية. 1,000 منحة لقادة استثنائيين.",
    "donate.programs.sustainability": "الاستدامة",
    "donate.programs.sustainability.desc": "200 منحة في هندسة الطاقة والزراعة لمستقبل فلسطين الأخضر.",
    "donate.programs.justice": "العدالة لفلسطين",
    "donate.programs.justice.desc": "200 منحة في العلوم السياسية والعلاقات الدولية للدعوة العالمية.",
    "donate.programs.ibn-khaldun": "Ibn Khaldun",
    "donate.programs.ibn-khaldun.desc": "200 scholarships in sociology and psychology for understanding Palestinian society.",
    "donate.programs.duration": "مدة البرنامج",
    "donate.programs.focus": "مجال التخصص",

    // Ibn Khaldun Scholarship translations
    "ibn-khaldun.title": "ابن خلدون",
    "ibn-khaldun.subtitle": "برنامج منحة العلوم الاجتماعية",
    "ibn-khaldun.tagline": "📚 فهم المجتمع الفلسطيني من خلال العلوم الاجتماعية 🧠",
    "ibn-khaldun.scholarships": "منح دراسية",
    "ibn-khaldun.fields": "مجالات رئيسية",
    "ibn-khaldun.years": "سنوات",
    "ibn-khaldun.about.title": "حول البرنامج الأكاديمي",
    "ibn-khaldun.about.desc": "ابن خلدون هو برنامج منح دراسية متخصص للدراسات العليا مصمم لتقديم 200 منحة دراسية كاملة في علم الاجتماع وعلم النفس للطلاب الفلسطينيين. يهدف البرنامج إلى تطوير كفاءات قادرة على فهم وتحليل الواقع الاجتماعي والنفسي للفلسطينيين لصياغة الحلول والسياسات العامة",
    "ibn-khaldun.apply": "قدم لمنحة ابن خلدون",
    "ibn-khaldun.download.en": "تحميل البرنامج (EN)",
    "ibn-khaldun.download.ar": "تحميل البرنامج (AR)",
    "ibn-khaldun.mission.title": "مهمتنا",
    "ibn-khaldun.mission.desc": "دعم وتطوير الكفاءات التي يمكنها فهم وتحليل الواقع الاجتماعي والنفسي للفلسطينيين لصياغة الحلول والسياسات العامة التي ترفع من شأن المجتمع الفلسطيني",
    "ibn-khaldun.fields.title": "مجالات الدراسة",
    "ibn-khaldun.fields.sociology.title": "علم الاجتماع",
    "ibn-khaldun.fields.sociology.desc": "دراسة شاملة للهياكل والمؤسسات والديناميكيات الاجتماعية داخل المجتمع الفلسطيني لفهم العلاقات المجتمعية والأنماط الثقافية",
    "ibn-khaldun.fields.sociology.points": ["النظرية الاجتماعية والبحث", "التنمية المجتمعية", "الدراسات الثقافية"],
    "ibn-khaldun.fields.psychology.title": "علم النفس",
    "ibn-khaldun.fields.psychology.desc": "دراسة متقدمة للعمليات النفسية الفردية والجماعية، والتعافي من الصدمات، وتدخلات الصحة العقلية المخصصة للتجارب الفلسطينية",
    "ibn-khaldun.fields.psychology.points": ["علم النفس السريري", "الصدمات والمرونة", "علم النفس المجتمعي"],
    "ibn-khaldun.requirements.title": "المتطلبات",
    "ibn-khaldun.requirements.nationality": "الجنسية الفلسطينية",
    "ibn-khaldun.requirements.degree": "بكالوريوس في العلوم الاجتماعية أو مجال ذي صلة",
    "ibn-khaldun.requirements.gpa": "معدل تراكمي 3.0+",
    "ibn-khaldun.requirements.research": "اهتمام بالبحث في القضايا الاجتماعية الفلسطينية",
    "ibn-khaldun.problems.title": "مؤشرات المشكلة",
    "ibn-khaldun.problems.experts": "نقص الخبراء في العلوم الاجتماعية",
    "ibn-khaldun.problems.experts.desc": "تشير التقارير المحلية إلى وجود فجوة كبيرة في عدد الأكاديميين والباحثين المؤهلين في علم الاجتماع مقارنة بحجم التحديات الاجتماعية والاقتصادية التي تتطلب تدخلات بحثية متخصصة.",
    "ibn-khaldun.problems.fragmentation": "تزايد التشرذم الاجتماعي والضغوط النفسية",
    "ibn-khaldun.problems.fragmentation.desc": "تشير الأنماط السلوكية الناشئة إلى أن نسبة كبيرة من الشباب الفلسطيني يعانون من أشكال التفكك الأسري أو الاجتماعي بسبب الحرب والنزوح والبطالة. وهذا يتطلب جهوداً بحثية تحليلية لفهم ومعالجة ديناميكيات المجتمع المتغيرة.",
    "ibn-khaldun.problems.research": "مؤسسات البحث المتخصصة تحت سيطرة الاحتلال",
    "ibn-khaldun.problems.research.desc": "تم توظيف الدراسة النفسية والاجتماعية والتاريخية للمجتمع الفلسطيني لأغراض السيطرة والهيمنة، حيث تم استخدام المعرفة النفسية والاجتماعية في استراتيجيات الاستعمار الناعم، مثل الحرب النفسية والإعلامية.",
    "ibn-khaldun.problems.local": "ضعف البحث المحلي في علم الاجتماع",
    "ibn-khaldun.problems.local.desc": "أقل من 3% من إنتاج فلسطين البحثي السنوي يركز على العلوم الاجتماعية. هناك انفصال كبير بين القضايا المجتمعية الحقيقية والإنتاج الأكاديمي القادر على تفسيرها ومعالجتها.",
    "ibn-khaldun.problems.programs": "برامج الدراسات العليا المحدودة في المجالات ذات الصلة",
    "ibn-khaldun.problems.programs.desc": "تقدم الجامعات الفلسطينية عدداً محدوداً جداً من برامج الماجستير والدكتوراه في علم الاجتماع أو المجالات ذات الصلة. غالباً ما تفتقر هذه البرامج إلى التدريب العملي والتكامل الفعال بين النظرية والسياقات الاجتماعية الواقعية.",
    "ibn-khaldun.problems.policy": "ضعف تكامل البحث والسياسة العامة",
    "ibn-khaldun.problems.policy.desc": "نادراً ما يتم استخدام مخرجات البحث الاجتماعي في صنع القرار. هناك نقص واضح في التنسيق بين الجامعات والمؤسسات الحكومية، مما يحد بشكل كبير من قدرة الباحثين على التأثير في تطوير السياسات الاجتماعية والتنموية.",
    "ibn-khaldun.contact.title": "اتصل بنا",
    "ibn-khaldun.contact.desc": "لمزيد من المعلومات، تواصل معنا:",
    "ibn-khaldun.apply.now": "قدم الآن",

    // Sustainability Scholarship Arabic translations
    "sustainability.title": " منحة الاستدامة",
    "sustainability.subtitle": "نحو السيادة العالمية ومجتمع يقود تنميته الذاتية",
    "sustainability.scholarships": "منح دراسية",
    "sustainability.years": "سنوات",
    "sustainability.majors": "تخصصات",
    "sustainability.pillars": "ركائز الدعم",
    "sustainability.about.title": "حول البرنامج",
    "sustainability.about.desc": "برنامج منحة الاستدامة للدراسات العليا هو مبادرة وطنية من مؤسسة إسناد لدعم الطلاب الفلسطينيين. يهدف إلى تأهيل المواهب الفلسطينية في المجالات الحيوية بما في ذلك الطاقة المستدامة والزراعة والموارد الطبيعية، لتحقيق السيادة الوطنية في الطاقة والغذاء، وتعزيز التنمية المستدامة في فلسطين.",
    "sustainability.why.title": "لماذا منحة الاستدامة؟",
    "sustainability.why.energy.title": "الاعتماد الكبير على الطاقة المستوردة",
    "sustainability.why.energy.desc": "تعتمد فلسطين على الطاقة المستوردة بنسبة 87.4% من احتياجاتها، مما يجعلها عرضة للأزمات ويؤثر على التنمية الاقتصادية والاجتماعية",
    "sustainability.why.renewable.title": "مساهمة منخفضة للطاقة المتجددة",
    "sustainability.why.renewable.desc": "رغم الإمكانات الطبيعية الكبيرة لفلسطين في الطاقة المتجددة، إلا أن مساهمتها في الإنتاج المحلي لا تتجاوز 4.7%",
    "sustainability.why.agriculture.title": "تحديات القطاع الزراعي",
    "sustainability.why.agriculture.desc": "يواجه القطاع الزراعي الفلسطيني تحديات كبيرة تتعلق بندرة المياه وتراجع المساحات المزروعة وضعف استخدام التقنيات الحديثة في الإنتاج النباتي والحيواني والغذائي",
    "sustainability.why.occupation.title": "تأثير الاحتلال على الموارد الطبيعية",
    "sustainability.why.occupation.desc": "يستنزف الاحتلال الموارد الطبيعية الفلسطينية ويحد من قدرة الفلسطينيين على الاستثمار فيها",
    "sustainability.why.programs.title": "نقص البرامج الأكاديمية المتخصصة",
    "sustainability.why.programs.desc": "هناك قلة في البرامج الأكاديمية المتخصصة في مجالات الطاقة والزراعة والموارد الطبيعية",
    "sustainability.why.research.title": "نقص البحث العلمي التطبيقي",
    "sustainability.why.research.desc": "هناك نقص في البحوث التطبيقية التي تساهم في تطوير حلول عملية للمشاكل المحلية",
    "sustainability.objectives.title": "أهدافنا",
    "sustainability.objectives.subtitle": "تمكين جيل جديد لقيادة مستقبل فلسطين المستدام, إليكم ما نسعى إليه",
    "sustainability.objectives.scholarships.title": "200 منحة دراسية كاملة",
    "sustainability.objectives.scholarships": " منحة دراسية كاملة للطلاب الفلسطينيين المتميزين في الطاقة والزراعة والموارد الطبيعية - تغذية الموجة القادمة من صناع التغيير",
    "sustainability.objectives.research.title": "البحث التطبيقي",
    "sustainability.objectives.research": "إشعال البحث العلمي التطبيقي الذي يقدم حلولاً حقيقية لفلسطين أكثر خضرة ومرونة",
    "sustainability.objectives.knowledge.title": "المعرفة والابتكار",
    "sustainability.objectives.knowledge": "تعزيز المعرفة والابتكار الفلسطيني، وربط البحث بالأولويات الوطنية والتأثير الواقعي",
    "sustainability.objectives.leaders.title": "قادة المستقبل",
    "sustainability.objectives.leaders": "إلهام وتخريج قادة مستعدين لقيادة التنمية المستدامة والتغيير الإيجابي في جميع أنحاء فلسطين",
    "sustainability.financial.title": "الدعم المالي",
    "sustainability.financial.tuition.title": "مقاعد دراسية",
    "sustainability.financial.tuition.desc": "تغطي المنحة الرسوم الدراسية السنوية",
    "sustainability.financial.tuition.amount": "دولار 3,000",
    "sustainability.financial.tuition.period": "أكاديمية سنة لكل",
    "sustainability.financial.living.title": "منحة شهرية",
    "sustainability.financial.living.desc": "المعيشة راتب شهري الطلاب يحصل",
    "sustainability.financial.living.amount": "دولار 200",
    "sustainability.financial.living.period": "شهرياً (2,400 دولار/سنة)",
    "sustainability.financial.housing.title": "دعم السكن",
    "sustainability.financial.housing.desc": "إذا لزم الأمر، توفر المنحة دعماً سنوياً للسكن",
    "sustainability.financial.housing.amount": "$2,400",
    "sustainability.financial.housing.period": "سنوياً",
    "sustainability.contact.title": "اتصل بنا",
    "sustainability.contact.desc": " : لمزيد من المعلومات، يرجى الاتصال بنا",
    "sustainability.apply": "قدم الآن",
    "sustainability.download.en": "تحميل البرنامج (EN)",
    "sustainability.download.ar": "تحميل البرنامج (AR)",

    // Palestinian Talented Scholarship translations
    "talented.title": "برنامج الموهوب  الفلسطيني",
    "talented.subtitle": "برنامج منحة الموهوب الفلسطيني",
    "talented.tagline": "🌟 دعم المواهب الفلسطينية: مسؤوليتنا الجماعية ⭐",
    "talented.scholarships": "منح دراسية",
    "talented.areas": "مجالات الدعم",
    "talented.pillars": "الركائز المالية",
    "talented.about.title": "حول برنامج الموهوب الفلسطيني",
    "talented.about.desc": "برنامج منحة الطالب الفلسطيني الموهوب هو مبادرة وطنية أطلقتها مؤسسة إسناد، تقدم 1,000 منحة دراسية للطلاب المتميزين داخل فلسطين في مختلف المجالات الأكاديمية. البرنامج مصمم لتطوير قادة استثنائيين في مختلف المجالات الأكاديمية وتمكين الشباب من تحقيق إمكاناتهم الكاملة وخدمة المجتمع.",
    "talented.apply": "قدم لمنحة الموهوب الفلسطيني",
    "talented.download.en": "تحميل البرنامج (EN)",
    "talented.download.ar": "تحميل البرنامج (AR)",
    "talented.why.title": "لماذا دعم المواهب الفلسطينية؟",
    "talented.why.programs.title": "نقص البرامج المتخصصة",
    "talented.why.programs.desc": "لا توجد برامج وطنية شاملة تدعم الطلاب المتميزين وتساعدهم على تحقيق إمكاناتهم في التميز الأكاديمي والمشاريع الابتكارية",
    "talented.why.environment.title": "الحرمان من البيئة التعليمية المناسبة",
    "talented.why.environment.desc": "بسبب نقص البنية التحتية التعليمية في فلسطين، العديد من الطلاب غير قادرين على الوصول إلى الموارد والأدوات التي يحتاجونها للتطوير والنجاح الأكاديمي",
    "talented.why.brain.title": "هجرة الأدمغة وفقدان المواهب المبكر",
    "talented.why.brain.desc": "غياب آليات الدعم المبكر للطلاب الاستثنائيين يؤدي إلى فقدان العديد من الأفراد الموهوبين الذين كان بإمكانهم المساهمة في مجتمعاتهم",
    "talented.why.development.title": "نقص برامج تطوير المواهب",
    "talented.why.development.desc": "الطلاب الفلسطينيون الموهوبون غالباً ما يفتقرون إلى الوصول للبرامج المتخصصة التي يمكنها رعاية مواهبهم ومساعدتهم على تطوير مهاراتهم والمساهمة في المجتمع",
    "talented.why.occupation.title": "ممارسات الاحتلال تؤثر سلباً على الرفاهية والفرص التعليمية",
    "talented.why.occupation.desc": "الاحتلال المستمر له تأثير سلبي على الرفاهية النفسية والتعليمية للطلاب. الضغط المستمر وعدم اليقين يجعل من الصعب التركيز على الأهداف التعليمية",
    "talented.why.economic.title": "الظروف الاقتصادية الصعبة تحد من الوصول للتعليم العالي",
    "talented.why.economic.desc": "القيود المالية والظروف الاقتصادية الصعبة تمنع العديد من الطلاب الفلسطينيين من متابعة التعليم العالي وتحقيق أحلامهم",
    "talented.why.achievement.title": "الإنجاز المتميز صعب التحقيق بدون دعم هامشي",
    "talented.why.achievement.desc": "لتحقيق نتائج متميزة، يحتاج الطلاب إلى دعم شامل يشمل المساعدة المالية والإرشاد والوصول إلى الموارد التعليمية المتقدمة",
    "talented.why.infrastructure.title": "وصول محدود للبنية التحتية التعليمية عالية الجودة",
    "talented.why.infrastructure.desc": "العديد من الطلاب الفلسطينيين يفتقرون إلى الوصول للمرافق التعليمية الحديثة والمختبرات المتقدمة والتكنولوجيا المتطورة الضرورية للتميز الأكاديمي والابتكار",
    "talented.goals.title": "أهدافنا",
    "talented.goals.scholarships": "منحة دراسية كاملة للطلاب الفلسطينيين المتميزين",
    "talented.goals.leaders": "تطوير قادة استثنائيين في مختلف المجالات الأكاديمية",
    "talented.goals.potential": "تمكين الشباب من تحقيق إمكاناتهم الكاملة وخدمة المجتمع",
    "talented.financial.title": "الدعم المالي لمنحة التميز",
    "talented.financial.academic.title": "مقاعد أكاديمية",
    "talented.financial.academic.desc": "تغطية كاملة لتكاليف برنامج الموهوب الفلسطيني",
    "talented.financial.academic.amount": "2,500 دولار",
    "talented.financial.academic.period": "لكل سنة أكاديمية",
    "talented.financial.stipend.title": "منحة شهرية",
    "talented.financial.stipend.desc": "دعم مصاريف المعيشة الشهرية",
    "talented.financial.stipend.amount": "200 دولار",
    "talented.financial.stipend.period": "شهرياً (2,400 دولار/سنة)",
    "talented.financial.technology.title": "منحة اقتناء أجهزة إلكترونية",
    "talented.financial.technology.desc": "دعم لمرة واحدة لشراء الأجهزة",
    "talented.financial.technology.amount": "300 دولار",
    "talented.financial.technology.period": "منحة لمرة واحدة",
    "talented.requirements.title": "المتطلبات",
    "talented.requirements.nationality": "الجنسية الفلسطينية",
    "talented.requirements.average": "معدل الثانوية العامة ≥ 90%",
    "talented.requirements.gpa": "معدل تراكمي 3.00+",
    "talented.requirements.english": "إجادة اللغة الإنجليزية مفضلة",
    "talented.fields.title": "مجالات الدراسة",
    "talented.fields.business": "إدارة الأعمال",
    "talented.fields.engineering": "الهندسة",
    "talented.fields.education": "التعليم",
    "talented.fields.social": "العلوم الاجتماعية",
    "talented.fields.computer": "علوم الحاسوب",
    "talented.fields.international": "العلاقات الدولية",
    "talented.fields.economics": "الاقتصاد",
    "talented.fields.law": "القانون",
    "talented.fields.psychology": "علم النفس",
    "talented.fields.media": "الإعلام والاتصالات",
    "talented.contact.title": "اتصل بنا",
    "talented.contact.desc": "For more information, reach out to us:",
    "talented.apply.now": "قدم الآن",

    // Home page News & Announcements section Arabic
    "news.badge": "آخر التحديثات",
    "news.title": "آخر الأخبار",
    "news.subtitle": "ابق على اطلاع علي آخر أخبارنا وتحديثاتنا والإعلانات المهمة من المؤسسة",
    "news.viewAll": "عرض جميع الأخبار",

    // Home page Our Programs section Arabic
    "programs.badge": "برامج المنح الدراسية",
    "programs.title": "برامجنا",
    "programs.subtitle": "تمكين الطلاب الفلسطينيين من خلال برامج المنح الدراسية المتخصصة",
    "programs.pulse.title": "منحة نبض الحياة",
    "programs.pulse.category": "الطب والعلوم الصحية",
    "programs.pulse.scholarships": "١,٠٠٠ منحة دراسية كاملة في الطب والعلوم الصحية",
    "programs.pulse.description": "مبادرة وطنية جريئة تقدم منحاً دراسية كاملة في الطب والعلوم الصحية، مع التركيز على التخصصات النادرة والحرجة لتعزيز الرعاية الصحية في فلسطين",
    "programs.pulse.focus": "تركيز البرنامج",
    "programs.pulse.features": "الميزات الرئيسية",
    "programs.pulse.medical": "التعليم الطبي",
    "programs.pulse.innovation": "الابتكار في الرعاية الصحية",
    "programs.pulse.full": "منح دراسية كاملة",
    "programs.pulse.years": "برنامج يمتد على مدى ٥ سنوات",
    "programs.talented.title": "منحة الموهوب الفلسطيني",
    "programs.talented.category": "منحة التميز",
    "programs.talented.scholarships": "برنامج يشمل ١,٠٠٠ منحة دراسية مخصصة للتميز",
    "programs.talented.description": "دعم الطلاب الفلسطينيين المتميزين في مختلف المجالات الأكاديمية، وتطوير قادة استثنائيين سيقودون الابتكار والتقدم في مجتمعاتهم",
    "programs.talented.focus": "تركيز البرنامج",
    "programs.talented.features": "الميزات الرئيسية",
    "programs.talented.excellence": "التميز الأكاديمي",
    "programs.talented.leadership": "القيادة الاستثنائية",
    "programs.talented.fields": "مجالات متعددة",
    "programs.talented.support": "دعم شامل",
    "programs.explore": "استكشف جميع البرامج",

    // Home page Your Path to Success section Arabic
    "journey.badge": "رحلة الطالب",
    "journey.title": "طريقك إلى النجاح",
    "journey.subtitle": "من التقديم إلى التخرج، نحن نقدم دعماً شاملاً في كل خطوة من رحلتك الأكاديمية",
    "journey.application.title": "التقديم",
    "journey.application.description": "قدم طلبك من خلال عمليتنا المبسطة. نحن نراجع كل طلب بعناية لتحديد المرشحين الواعدين",
    "journey.application.form": "نموذج التقديم الإلكتروني",
    "journey.application.documents": "تقديم الوثائق",
    "journey.application.screening": "الفحص الأولي",
    "journey.selection.title": "الاختيار",
    "journey.selection.description": "تقوم لجنتنا الخبيرة بتقييم المرشحين بناءً على التميز الأكاديمي والإمكانات القيادية والالتزام بالمجتمع",
    "journey.selection.review": "المراجعة الأكاديمية",
    "journey.selection.interview": "عملية المقابلة",
    "journey.selection.final": "الاختيار النهائي",
    "journey.support.title": "الدعم",
    "journey.support.description": "احصل على دعم شامل طوال رحلتك الأكاديمية، بما في ذلك المساعدة المالية والإرشاد والتوجيه المهني",
    "journey.support.financial": "الدعم المالي",
    "journey.support.mentoring": "الإرشاد الأكاديمي",
    "journey.support.career": "التطوير المهني",
    "journey.success.title": "النجاح",
    "journey.success.description": "انضم إلى شبكة خريجينا الناجحين الذين يحدثون فرقاً في مجتمعاتهم وما بعدها",
    "journey.success.graduation": "دعم التخرج",
    "journey.success.alumni": "شبكة الخريجين",
    "journey.success.opportunities": "الفرص المهنية",
    "journey.start": "ابدأ رحلتك",

    // Home page Call to Action section Arabic
    "cta.title": "انضم إلينا لتمكين الطلاب الفلسطينيين",
    "cta.description": "يمكن لدعمك أن يحدث تأثيراً دائماً في حياة الطلاب الفلسطينيين الموهوبين. معاً، يمكننا بناء مستقبل أكثر إشراقاً من خلال التعليم",
    "cta.button": "تبرع الآن",

    // Home page Partners section Arabic
    "partners.badge": "شركاؤنا",
    "partners.title": "العمل معاً من أجل التغيير",
    "partners.subtitle": "نحن نتعاون مع المؤسسات والمنظمات الرائدة لتقديم دعم شامل للطلاب الفلسطينيين",

    // Home page Contact section Arabic
    "contact.badge": "تواصل معنا",
    "contact.button": "تواصل مع فريقنا",

    // Stats section Arabic
    "stats.scholarships": "منح دراسية مقدمة",
    "stats.beneficiaries": "مستفيد",
    "stats.countries": "دول مستفيدة",
    "stats.graduation": "معدل التخرج %",

    // Footer section Arabic
    "footer.description": "تمكين الطلاب الفلسطينيين حول العالم من خلال الفرص التعليمية والدعم المالي والموارد الأكاديمية",
    "footer.programs.undergraduate": "برامج البكالوريوس",
    "footer.programs.graduate": "برامج الدراسات العليا",
    "footer.programs.research": "برامج البحث",
    "footer.about.mission": "رسالتنا",
    "footer.about.team": "الفريق",
    "footer.about.partners": "الشركاء",

    // About page specific translations Arabic
    "about.page.indicator": "من نحن",
    "about.purpose.badge": "هدفنا",
    "about.purpose.title": "الرسالة والرؤية",
    "about.purpose.subtitle": "مسترشدين بالتزامنا بالعدالة التعليمية وتمكين الطلاب الفلسطينيين حول العالم",
    "about.mission.point1": "تقديم منح دراسية للطلاب الفلسطينيين الموهوبين",
    "about.mission.point2": "خلق فرص تعليمية من خلال الشراكات العالمية",
    "about.mission.point3": "دعم التطوير الأكاديمي والمهني",
    "about.vision.point1": "عالم يحصل فيه كل طالب فلسطيني على تعليم عالي الجودة",
    "about.vision.point2": "شبكة عالمية من الأكاديميين والمهنيين الفلسطينيين",
    "about.vision.point3": "التمكين التعليمي كطريق لتنمية المجتمع",
    "about.partners.badge": "التعاون",
    "about.partners.title": "شركاؤنا",
    "about.partners.subtitle": "نحن نتعاون مع الجامعات والمؤسسات التعليمية والمنظمات حول العالم لتوسيع الفرص للطلاب الفلسطينيين",
    "about.cta.title": "انضم إلينا",
    "about.cta.subtitle": "سواء كنت طالباً تبحث عن الدعم، أو شريكاً محتملاً، أو شخصاً يريد المساهمة في قضيتنا، نحن نحب أن نسمع منك",
    "about.cta.contact": "اتصل بنا",
    "about.cta.support": "ادعم عملنا",

    // Pulse of Life page translations Arabic
    "pulse.title": "منحة نبض الحياة",
    "pulse.subtitle": "برنامج المنح الطبية",
    "pulse.tagline": "🩺 صحة فلسطين... مسؤوليتنا 🏥",
    "pulse.stats.scholarships": "منحة دراسية",
    "pulse.stats.years": "سنوات",
    "pulse.stats.pillars": "ركائز الدعم",
    "pulse.about.title": "عن البرنامج",
    "pulse.about.description": "هي مبادرة وطنية جريئة أطلقتها مؤسسة الإسناد، تهدف إلى تقديم 1,000 منحة دراسية كاملة في الطب والعلوم الصحية للطلاب الفلسطينيين داخل وخارج فلسطين—خاصة في التخصصات النادرة والحرجة. البرنامج مصمم ليعمل على مدى فترة 5 سنوات",
    "pulse.apply": "قدم لمنحة نبض الحياة",
    "pulse.download.en": "تحميل البرنامج (EN)",
    "pulse.download.ar": "تحميل البرنامج (AR)",
    "pulse.why.title": "لماذا نبض الحياة؟",
    "pulse.why.shortage.title": "نقص في الكوادر الطبية",
    "pulse.why.shortage.description": "هناك نقص حاد في المهنيين الطبيين والصحيين المؤهلين، مما يحد من تقديم الخدمات ويقلل من جودة الرعاية في المؤسسات الصحية",
    "pulse.why.specialized.title": "نقص في المجالات المتخصصة",
    "pulse.why.specialized.description": "يعاني النظام الصحي المحلي من نقص في المتخصصين في المجالات الطبية الرئيسية، مما يزيد الضغط على وزارة الصحة ويحد من خيارات الرعاية المتقدمة",
    "pulse.why.capacity.title": "نقص في السعة الاستيعابية للمستشفيات",
    "pulse.why.capacity.description": "نقص في أسرة المستشفيات والموارد الأساسية يعني أن العديد من المرضى لا يمكنهم الحصول على الرعاية في الوقت المناسب، مما يؤدي إلى ارتفاع معدلات الوفيات وإرهاق المرافق الموجودة.",
    "pulse.why.infrastructure.title": "ضعف البنية التحتية للرعاية الصحية",
    "pulse.why.infrastructure.description": "العديد من الأجهزة الطبية خارج الخدمة، والموارد الأساسية لتشغيل المرافق الصحية بكفاءة مفقودة، مما يجعل من الصعب تقديم الرعاية المناسبة",
    "pulse.why.occupation.title": "تأثير الاحتلال الإسرائيلي",
    "pulse.why.occupation.description": "منذ عام 2023، دمرت الهجمات الإسرائيلية المستمرة العديد من المرافق الصحية، مما حد بشدة من القدرة على تقديم الخدمات وقلل من القدرة الإجمالية للنظام الصحي",
    "pulse.goals.title": "أهدافنا",
    "pulse.goals.train": "تدريب 1,000 طالب في الطب والعلوم الصحية من خلال منح دراسية كاملة",
    "pulse.goals.support": "دعم الرعاية الصحية المحلية من خلال دمج الخريجين في النظام",
    "pulse.goals.reach": "الوصول إلى المناطق المحرومة من خلال العيادات المتنقلة وجهود التوعية",
    "pulse.financial.title": "الدعم المالي لمنحة نبض الحياة",
    "pulse.financial.education.title": "مقاعد دراسية",
    "pulse.financial.education.description": "تغطية كاملة لتكاليف التعليم الطبي",
    "pulse.financial.education.amount": "$5,600",
    "pulse.financial.education.period": "لكل سنة أكاديمية",
    "pulse.financial.stipend.title": "منحة شهرية",
    "pulse.financial.stipend.description": "دعم مصاريف المعيشة الشهرية",
    "pulse.financial.stipend.amount": "$200",
    "pulse.financial.stipend.period": "شهرياً ($2,400/سنة)",
    "pulse.financial.technology.title": "منحة اقتناء أجهزة إلكترونية",
    "pulse.financial.technology.description": "دعم لمرة واحدة لشراء الأجهزة",
    "pulse.financial.technology.amount": "$300",
    "pulse.financial.technology.period": "منحة لمرة واحدة",
    "pulse.requirements.title": "المتطلبات",
    "pulse.requirements.nationality": "الجنسية الفلسطينية",
    "pulse.requirements.average": "معدل الثانوية العامة ≥ 90%",
    "pulse.requirements.gpa": "معدل تراكمي 3.00+",
    "pulse.requirements.english": "إجادة اللغة الإنجليزية مفضلة",
    "pulse.fields.title": "مجالات الدراسة",
    "pulse.fields.medicine": "الطب البشري",
    "pulse.fields.dentistry": "طب الأسنان",
    "pulse.fields.pharmacy": "الصيدلة",
    "pulse.fields.allied": "المهن الصحية المساعدة",
    "pulse.fields.nursing": "التمريض",
    "pulse.apply.now": "قدم الآن",
    "pulse.news.title": "آخر تحديثات البرنامج",
    "pulse.news.subtitle": "مؤسسة إسناد تبدأ صرف منح برنامج نبض الحياة بالشراكة مع جمعية الشباب الوطني التركي (MGV)",
    "pulse.news.disbursement.title": "بدء صرف المنح",
    "pulse.news.disbursement.description": "بدأت المرحلة الأولى من صرف منح نبض الحياة رسمياً في تركيا، لدعم الطلاب الفلسطينيين في الطب",
    "pulse.news.watch.videos": "شاهد أحدث الفيديوهات",
    "pulse.news.read.more": "اقرأ المقال كاملاً",
    "pulse.contact.title": "اتصل بنا",
    "pulse.contact.description": ":لمزيد من المعلومات، تواصل معنا",

    // Justice for Palestine Arabic translations
    "justice.title": "العدالة لفلسطين",
    "justice.subtitle": "برنامج منحة العدالة لفلسطين",
    "justice.tagline": "⚖️ إعداد قادة فلسطينيين للدعوة العالمية 🇵🇸",
    "justice.scholarships": "منح دراسية",
    "justice.fields": "مجالات رئيسية",
    "justice.years": "سنوات",
    "justice.about.title": "عن برنامج العدالة",
    "justice.about.desc": "العدالة لفلسطين هو برنامج منح دراسية متخصص للدراسات العليا مصمم لتقديم 200 منحة دراسية كاملة في العلوم السياسية والعلاقات الدولية للطلاب الفلسطينيين. يهدف البرنامج إلى إعداد كفاءات فلسطينية مؤهلة للدور السياسي والدبلوماسي والدولي وإدارة الأزمات لتمكينهم من الدعوة لفلسطين عالمياً وتعزيز القضية الفلسطينية على الساحة الدولية",
    "justice.apply": "قدم لمنحة العدالة",
    "justice.download.en": "تحميل البرنامج (EN)",
    "justice.download.ar": "تحميل البرنامج (AR)",
    "justice.mission.title": "مهمتنا",
    "justice.mission.desc": "إعداد كفاءات فلسطينية مؤهلة للدور السياسي والدبلوماسي والدولي وإدارة الأزمات لتمكينهم من الدعوة لفلسطين عالمياً وتعزيز القضية الفلسطينية على الساحة الدولية",
    "justice.fields.title": "مجالات الدراسة",
    "justice.fields.political.title": "العلوم السياسية",
    "justice.fields.political.desc": "دراسات متقدمة في النظرية السياسية والحوكمة وتحليل السياسات العامة والفهم السياسي لتطوير الخبرة في فهم النظم السياسية",
    "justice.fields.political.points": ["النظرية السياسية", "تحليل السياسات العامة", "السياسة المقارنة"],
    "justice.fields.international.title": "العلاقات الدولية",
    "justice.fields.international.desc": "تدريب شامل في الدبلوماسية والقانون الدولي وحل النزاعات والحوكمة العالمية لأدوار الدعوة الدولية",
    "justice.fields.international.points": ["الدراسات الدبلوماسية", "القانون الدولي", "حل النزاعات"],
    "justice.requirements.title": "المتطلبات",
    "justice.requirements.nationality": "الجنسية الفلسطينية",
    "justice.requirements.degree": "بكالوريوس في العلوم السياسية أو القانون أو مجال ذي صلة",
    "justice.requirements.gpa": "معدل تراكمي 3.0+",
    "justice.requirements.interest": "الاهتمام بالدعوة السياسية والدولية",
    "justice.contact.title": "اتصل بنا",
    "justice.contact.description": "لمزيد من المعلومات حول برنامج منحة العدالة لفلسطين، تواصل معنا:",
    "justice.contact.desc": "For more information, reach out to us:",

    // News page translations
    "news.hero.alt": "صورة الأخبار الرئيسية",
    "news.latest": "آخر الأخبار",
    "news.featured.badge": "مميز",
    "news.featured.title": "قصص مميزة",
    "news.featured.subtitle": "تسليط الضوء على أهم تحديثاتنا وإعلاناتنا",
    "news.archive.badge": "الأرشيف",
    "news.archive.title": "أرشيف الأخبار",
    "news.archive.subtitle": "تصفح مجموعتنا الكاملة من الأخبار والتحديثات والإعلانات",
    "news.search.placeholder": "البحث في الأخبار...",
    "news.filter.placeholder": "تصفية حسب الفئة",
    "news.tabs.all": "جميع الأخبار",
    "news.tabs.featured": "مميز",
    "news.tabs.recent": "حديث",
    "news.readMore": "اقرأ المزيد",
    "news.noResults": "لم يتم العثور على مقالات إخبارية تطابق معايير البحث.",
    "news.backToNews": "العودة إلى الأخبار",
    "news.moreNews": "المزيد من الأخبار",
    "news.moreNewsDesc": "استكشف المزيد من مقالاتنا الإخبارية والتحديثات",
    "news.viewprograms": "تصفح برامجنا",
    "news.relatedArticles": "مقالات ذات صلة",
    "news.categories": "التصنيفات",
    "news.explorePrograms": "استكشف برامجنا",
    "news.exploreProgramsDesc": "اكتشف برامج المنح الدراسية ومبادراتنا التعليمية",
    "news.viewPrograms": "عرض جميع البرامج",
    "news.share": "مشاركة المقال",
    "news.linkCopied": "تم نسخ الرابط إلى الحافظة",

    "news.latest.supportTour.title": "مؤسسة إسنَاد لدعم الطالب الفلسطيني تنفذ جولات دعم في ست دول وتقدم منحًا تعليمية لطلاب غزة",
    "news.latest.supportTour.excerpt": "نفذت مؤسسة إسنَاد لدعم الطالب الفلسطيني منذ بدء حرب الإبادة في قطاع غزة  سلسلة من اللقاءات والفعاليات في عدد من الدول شملت تركيا، مصر، موريتانيا، قرغيزستان، ماليزيا، وقطاع غزة، وذلك في إطار استجابتها العاجلة لاحتياجات الطلبة الفلسطينيين المتضررين من الحرب المستمرة على قطاع غزة منذ أكتوبر 2023.",
    "news.latest.supportTour.category": "Education & Humanitarian Support",
    "news.latest.supportTour.date": "June 06, 2024",

    "news.latest.pulseOfLifeStart.title": "استمرار مقابلات المرحلة الأولى من منحة نبض الحياة لاختيار 100 طالب من غزة للاستفادة من البرنامج",
    "news.latest.pulseOfLifeStart.excerpt": "تواصلت اليوم الإثنين مقابلات المرحلة الأولى من برنامج منحة نبض الحياة، الذي تنفذه مؤسسة إسنَاد لدعم الطالب الفلسطيني بالشراكة مع مؤسسة الخدمات أوروبا (Alkhidmat Europe)، والتي تستهدف طلبة الطب الفلسطينيين خاصة في قطاع غزة.",
    "news.latest.pulseOfLifeStart.category": "Scholarships",
    "news.latest.pulseOfLifeStart.date": "May 5, 2025",

    "news.latest.pulseOfLifeEnd.title": "انتهاء المرحلة الأولى من مقابلات منحة نبض الحياة",
    "news.latest.pulseOfLifeEnd.excerpt": "اختتمت مؤسسة إسناد لدعم الطالب الفلسطيني، يوم السبت الموافق 25 مايو 2025، المرحلة الأولى من مقابلات منحة \"نبض الحياة\"، والتي امتدت على مدار ثلاثة أسابيع بدءًا من الخامس من مايو، بمشاركة عشرات الطلبة الفلسطينيين المتفوقين في تخصص الطب البشري.",
    "news.latest.pulseOfLifeEnd.category": "Scholarships",
    "news.latest.pulseOfLifeEnd.date": "May 25, 2025",

    "stats.partners": "الشركاء",
    "stats.pillars": "ركائز الدعم",

    // Contact page translations
    "contact.getInTouch": "تواصل معنا",
    "contact.title": "تواصل معنا",
    "contact.subtitle": "هل لديك أسئلة حول برامجنا أو عملية التقديم؟ فريقنا هنا لمساعدتك في رحلتك التعليمية.",
    "contact.phone": "+90 (539) 4300 726",
    "contact.email": "info@isnadf.org",
    "contact.info.title": "معلومات الاتصال",
    "contact.info.subtitle": "في حال كان لديك أسئلة حول برامجنا، أو عملية التقديم، أو ترغب في معرفة المزيد عن مؤسستنا، فنحن هنا لمساعدتك.",
    "contact.location.title": "موقعنا",
    "contact.location.address": "Kayabaşı Mah. Adnan Menderes Blv. A4 Blok No:7A Kapı No:11 Başakşehir/İstanbul",
    "contact.email.title": "راسلنا عبر البريد الإلكتروني",
    "contact.email.secondary": "Palestinian.pssf@gmail.com",
    "contact.phone.title": "اتصل بنا",
    "contact.phone.hours": "الاثنين-الجمعة، 9:00 صباحاً - 5:00 مساءً (توقيت GMT+3)",
    "contact.follow.title": "تابعنا",
    "contact.form.title": "أرسل لنا رسالة",
    "contact.form.subtitle": "املأ النموذج أدناه وسنرد عليك في أقرب وقت ممكن.",
    "contact.form.name": "اسمك",
    "contact.form.name.placeholder": "أدخل اسمك",
    "contact.form.email": "البريد الإلكتروني",
    "contact.form.email.placeholder": "أدخل بريدك الإلكتروني",
    "contact.form.subject": "الموضوع",
    "contact.form.subject.placeholder": "أدخل الموضوع",
    "contact.form.message": "الرسالة",
    "contact.form.message.placeholder": "أدخل رسالتك",
    "contact.form.submit": "إرسال الرسالة",
    "contact.map.title": "موقعنا",
    "contact.office.title": "ألق نظرة من الداخل",
    "contact.office.subtitle":"اطلع علي لمحة من مساحة مكتبنا حيث نعمل علي دعم الطلاب الفلسطينيين في رحلتهم التعليمية.",
    "contact.office.entrance": "مدخل المكتب",
    "contact.office.workspace": "مساحة العمل",
    "contact.office.meeting": "غرفة الاجتماعات",

    "contact.info.subtitle2": "Reach out to us using any of the methods below.",

    // Success Stories Arabic translations
    "success_stories.page_indicator": "قصص النجاح",
    "success_stories.title": "قصص النجاح",
    "success_stories.subtitle": "تعرف على الطلاب المتميزين الذين غيروا حياتهم من خلال برامج الدعم لدينا",
    "success_stories.inspiring_journeys": "رحلات ملهمة",
    "success_stories.featured_stories": "قصص مميزة",
    "success_stories.featured_description": "رحلات ملهمة من التصميم والمرونة والتميز الأكاديمي",
    "success_stories.mandela_quote": "التعليم هو أقوى سلاح يمكنك استخدامه لتغيير العالم",
    "success_stories.mandela_author": "نيلسون مانديلا",
    "success_stories.browse_stories": "تصفح القصص",
    "success_stories.all_stories": "جميع قصص النجاح",
    "success_stories.browse_description": "تصفح رحلات طلاب المنح الدراسية الملهمة",
    "success_stories.search_placeholder": "البحث في القصص...",
    "success_stories.degree_level": "المستوى الأكاديمي",
    "success_stories.graduation_year": "سنة التخرج",
    "success_stories.tabs.all": "جميع القصص",
    "success_stories.tabs.featured": "مميزة",
    "success_stories.read_full_story": "قراءة القصة كاملة",
    "success_stories.no_stories_found": "لم يتم العثور على قصص نجاح تطابق معايير البحث.",
    "success_stories.your_journey_matters": "رحلتك مهمة",
    "success_stories.share_story_title": "شارك قصتك",
    "success_stories.share_story_description": "هل أنت من مستفيدي المنح الدراسية ولديك قصة ترويها؟ نحن نود أن نشارك رحلتك ونلهم الآخرين",
    "success_stories.submit_story": "قدم قصتك",
    "success_stories.categories.bachelors": "بكالوريوس",
    "success_stories.categories.masters": "ماجستير",
    "success_stories.categories.phd": "دكتوراه",
    "success_stories.back_to_stories": "العودة إلى القصص",

    "testimonials.hero.title": "بصمة إسناد في مسيرة طلابنا",
    "testimonials.hero.subtitle": "استمع مباشرة من الطلاب عن تجاربهم وتأثير برامجنا",
    "testimonials.hero.subtitle_influencers": "استمع مباشرة من العلماء والشخصيات العامة عن تجاربهم وتأثير برامجنا",
    "testimonials.student_voices": "طلاب مستفيدون",
    "testimonials.student_testimonials": "شهادات الطلاب",
    "testimonials.student_description": "شاهد ماذا قال الطلاب الفلسطينيين عن مؤسستنا",
    "testimonials.public_figures": "شخصيات عامة",
    "testimonials.public_figure_testimonials": "شهادات الشخصيات العامة",
    "testimonials.public_figure_description": "نفخر بشهادة شخصيات وازنة  عن مؤسستنا\nتعني لنا الكثير، وتُعطينا دافعًا\nلاستكمال السعي نحو خدمة الطلاب الفلسطينين حول العالم",
    "ibn-khaldun.financial.title": "هيكل الدعم المالي",
    "ibn-khaldun.financial.tuition.title": "دعم الرسوم الدراسية",
    "ibn-khaldun.financial.stipend.title": "المنحة الشهرية",
    "ibn-khaldun.financial.total.title": "إجمالي الدعم المالي",
    "ibn-khaldun.financial.tuition.desc": "تغطي تكاليف الرسوم الدراسية في مختلف التخصصات، بمتوسط دعم سنوي قدره 3,000 دولار لكل طالب.",
    "ibn-khaldun.financial.stipend.desc": "توفر بدل شهري متوسط قدره 200 دولار لدعم احتياجات الطلاب الأساسية، مثل السكن والنقل، بإجمالي 2,400 دولار سنوياً.",
    "ibn-khaldun.financial.total.annual": "إجمالي التكلفة السنوية لكل طالب",
    "ibn-khaldun.financial.total.fiveYear": "إجمالي التكلفة لمدة 5 سنوات لكل طالب",
    "ibn-khaldun.financial.perYear": "سنوياً",
    "ibn-khaldun.financial.note": "ملاحظة: قد تختلف التكاليف الفعلية حسب الجامعة وبرنامج الدراسة.",

    // Programs page translations
    "programs.hero.title": "برامج المنح الدراسية",
    "programs.hero.subtitle": "تمكين الطلاب الفلسطينيين من خلال التميز التعليمي",
    "programs.hero.flag.alt": "علم فلسطين",
    "programs.section.title": "برامجنا",
    "programs.section.subtitle": "اختر مسارك نحو التميز التعليمي",
    "programs.undergraduate.title": "برامج البكالوريوس",
    "programs.postgraduate.title": "برامج الدراسات العليا",
    "programs.postgraduate.subtitle": "درجات متقدمة للخبرة المتخصصة",
    "programs.sustainability.title": "الاستدامة",
    "programs.sustainability.description": "200 منحة في هندسة الطاقة والزراعة لمستقبل فلسطين الأخضر.",
    "programs.justice.title": "العدالة لفلسطين",
    "programs.justice.description": "200 منحة في العلوم السياسية والعلاقات الدولية للدعوة العالمية.",
    "programs.ibn-khaldun.title": "ابن خلدون",
    "programs.ibn-khaldun.description": "200 منحة في علم الاجتماع وعلم النفس لفهم المجتمع الفلسطيني.",
    "programs.learn-more": "اعرف المزيد",
  },
}

// Remove duplicate translations
const cleanTranslations = {
  en: Object.fromEntries(
    Object.entries(translations.en).filter(([key], index, self) => 
      index === self.findIndex(([k]) => k === key)
    )
  ),
  ar: Object.fromEntries(
    Object.entries(translations.ar).filter(([key], index, self) => 
      index === self.findIndex(([k]) => k === key)
    )
  )
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "ar"].includes(savedLanguage)) {
      setLanguageState(savedLanguage)
      document.documentElement.lang = savedLanguage
      document.documentElement.dir = savedLanguage === "ar" ? "rtl" : "ltr"
    } else {
      // Set default to Arabic if no saved language
      document.documentElement.lang = "ar"
      document.documentElement.dir = "rtl"
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
  }

  const t = (key: string): string | string[] => {
    return cleanTranslations[language][key as keyof (typeof cleanTranslations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

